import {BadRequestException,Body,Controller,Get,NotFoundException,Param,Post,Put} from '@nestjs/common';
import {ModelConfigurationSchema,ModelManifestSchema} from '@product3d/model-schema';
import {Prisma} from '@prisma/client';
import {PrismaService} from '../prisma/prisma.service';
import {ExportQueueService} from '../queue/export-queue.service';

@Controller('projects')
export class ProjectController{
  constructor(private readonly db:PrismaService,private readonly exports:ExportQueueService){}
  @Post() async create(@Body()body:{userId:string;modelAssetId:string;name:string}){const[user,asset]=await Promise.all([this.db.user.findUnique({where:{id:body.userId}}),this.db.modelAsset.findUnique({where:{id:body.modelAssetId}})]);if(!user)throw new BadRequestException('User does not exist.');if(!asset)throw new BadRequestException('Model asset does not exist.');return this.db.project.create({data:body});}
  @Get(':id') async get(@Param('id')id:string){const project=await this.db.project.findUnique({where:{id},include:{versions:{orderBy:{createdAt:'desc'}},modelAsset:true}});if(!project)throw new NotFoundException('Project not found.');return project;}
  @Put(':id') update(@Param('id')id:string,@Body()body:{name?:string;activeVersionId?:string}){return this.db.project.update({where:{id},data:body});}
  @Post(':id/versions') async saveVersion(@Param('id')id:string,@Body()body:{name:string;configurationJson:unknown;previewUrl?:string}){const configuration=ModelConfigurationSchema.safeParse(body.configurationJson);if(!configuration.success)throw new BadRequestException(configuration.error.flatten());const project=await this.db.project.findUnique({where:{id},include:{modelAsset:{include:{manifests:{orderBy:{version:'desc'},take:1}}}}});if(!project)throw new NotFoundException('Project not found.');const latestManifest=project.modelAsset.manifests[0];if(!latestManifest)throw new BadRequestException('Asset has no saved manifest.');if(configuration.data.modelId!==ModelManifestSchema.parse(latestManifest.manifestJson).modelId)throw new BadRequestException('Configuration modelId does not match project manifest.');const version=await this.db.modelVersion.create({data:{projectId:id,name:body.name,configurationJson:configuration.data as Prisma.InputJsonValue,previewUrl:body.previewUrl}});await this.db.project.update({where:{id},data:{activeVersionId:version.id}});return version;}
  @Get(':id/versions') versions(@Param('id')id:string){return this.db.modelVersion.findMany({where:{projectId:id},orderBy:{createdAt:'desc'}});}
  @Post(':id/duplicate') async duplicate(@Param('id')id:string){const source=await this.db.project.findUnique({where:{id},include:{versions:{orderBy:{createdAt:'desc'}}}});if(!source)throw new NotFoundException('Project not found.');return this.db.$transaction(async tx=>{const copy=await tx.project.create({data:{userId:source.userId,modelAssetId:source.modelAssetId,name:`${source.name} Copy`}});const versions=[];for(const version of source.versions){versions.push(await tx.modelVersion.create({data:{projectId:copy.id,name:version.name,configurationJson:version.configurationJson as Prisma.InputJsonValue,previewUrl:version.previewUrl}}));}if(versions.length)await tx.project.update({where:{id:copy.id},data:{activeVersionId:versions[0].id}});return tx.project.findUniqueOrThrow({where:{id:copy.id},include:{versions:true}});});}
  @Post(':id/export') async export(@Param('id')id:string,@Body()body:{versionId?:string;configurationJson?:unknown}){const project=await this.db.project.findUnique({where:{id},include:{modelAsset:{include:{manifests:{orderBy:{version:'desc'},take:1}}}}});if(!project)throw new NotFoundException('Project not found.');if(!project.modelAsset.sourceObjectKey)throw new BadRequestException('Project asset has no source object.');const manifestRecord=project.modelAsset.manifests[0];if(!manifestRecord)throw new BadRequestException('Project asset has no saved manifest.');const manifest=ModelManifestSchema.parse(manifestRecord.manifestJson);let rawConfig=body.configurationJson;if(body.versionId){const version=await this.db.modelVersion.findFirst({where:{id:body.versionId,projectId:id}});if(!version)throw new NotFoundException('Version not found in this project.');rawConfig=version.configurationJson;}if(!rawConfig&&project.activeVersionId){const version=await this.db.modelVersion.findFirst({where:{id:project.activeVersionId,projectId:id}});rawConfig=version?.configurationJson;}const configuration=ModelConfigurationSchema.safeParse(rawConfig);if(!configuration.success)throw new BadRequestException('Provide a valid configurationJson, versionId, or active project version.');if(configuration.data.modelId!==manifest.modelId)throw new BadRequestException('Configuration and manifest modelId do not match.');const dbJob=await this.db.job.create({data:{type:'GLB_EXPORT',status:'QUEUED',modelAssetId:project.modelAssetId,payload:{projectId:id,versionId:body.versionId??null}}});try{const queued=await this.exports.enqueue({databaseJobId:dbJob.id,projectId:id,assetId:project.modelAssetId,sourceObjectKey:project.modelAsset.sourceObjectKey,manifest,configuration:configuration.data,filename:`${project.name.replace(/[^a-zA-Z0-9_-]+/g,'_')||'product'}.glb`});await this.db.job.update({where:{id:dbJob.id},data:{bullmqJobId:String(queued.id)}});return{jobId:dbJob.id,status:'QUEUED'};}catch(error){await this.db.job.update({where:{id:dbJob.id},data:{status:'FAILED',failureReason:error instanceof Error?error.message:String(error)}});throw error;}}
}
