import {BadRequestException,Body,Controller,Get,NotFoundException,Param,Post,Put,Req,UseGuards} from '@nestjs/common';import {ModelConfigurationSchema,ModelManifestSchema} from '@product3d/model-schema';import {Prisma} from '@prisma/client';import {AuthRequest,requireAuthUser,SupabaseAuthGuard} from '../auth/auth.service';import {PrismaService} from '../prisma/prisma.service';import {ExportQueueService} from '../queue/export-queue.service';
@Controller('projects') @UseGuards(SupabaseAuthGuard)
export class ProjectController{constructor(private readonly db:PrismaService,private readonly exports:ExportQueueService){}
 private async owned(id:string,userId:string,include?:object){const project=await this.db.project.findFirst({where:{id,userId},include:include as never});if(!project)throw new NotFoundException('Project not found.');return project as any}
 @Get() list(@Req()r:AuthRequest){return this.db.project.findMany({where:{userId:requireAuthUser(r).id},include:{modelAsset:{select:{id:true,name:true,status:true,thumbnailUrl:true}},versions:{select:{id:true,name:true,createdAt:true},orderBy:{createdAt:'desc'},take:1}},orderBy:{updatedAt:'desc'}})}
 @Post() async create(@Req()r:AuthRequest,@Body()body:{modelAssetId:string;name:string}){const user=requireAuthUser(r),asset=await this.db.modelAsset.findFirst({where:{id:body.modelAssetId,ownerId:user.id}});if(!asset)throw new BadRequestException('Model asset does not belong to the authenticated user.');return this.db.project.create({data:{userId:user.id,modelAssetId:body.modelAssetId,name:body.name}})}
 @Get(':id') get(@Req()r:AuthRequest,@Param('id')id:string){return this.owned(id,requireAuthUser(r).id,{versions:{orderBy:{createdAt:'desc'}},modelAsset:true})}
 @Put(':id') async update(@Req()r:AuthRequest,@Param('id')id:string,@Body()body:{name?:string;activeVersionId?:string}){const user=requireAuthUser(r);await this.owned(id,user.id);if(body.activeVersionId){const version=await this.db.modelVersion.findFirst({where:{id:body.activeVersionId,projectId:id}});if(!version)throw new BadRequestException('Active version must belong to the project.');}return this.db.project.update({where:{id},data:body})}
 @Post(':id/versions') async saveVersion(@Req()r:AuthRequest,@Param('id')id:string,@Body()body:{name:string;configurationJson:unknown;previewUrl?:string}){const user=requireAuthUser(r),configuration=ModelConfigurationSchema.safeParse(body.configurationJson);if(!configuration.success)throw new BadRequestException(configuration.error.flatten());const project=await this.db.project.findFirst({where:{id,userId:user.id},include:{modelAsset:{include:{manifests:{orderBy:{version:'desc'},take:1}}}}});if(!project)throw new NotFoundException('Project not found.');const latestManifest=project.modelAsset.manifests[0];if(!latestManifest)throw new BadRequestException('Asset has no saved manifest.');if(configuration.data.modelId!==ModelManifestSchema.parse(latestManifest.manifestJson).modelId)throw new BadRequestException('Configuration modelId does not match project manifest.');const version=await this.db.modelVersion.create({data:{projectId:id,name:body.name,configurationJson:configuration.data as Prisma.InputJsonValue,previewUrl:body.previewUrl}});await this.db.project.update({where:{id},data:{activeVersionId:version.id}});return version}
 @Get(':id/versions') async versions(@Req()r:AuthRequest,@Param('id')id:string){await this.owned(id,requireAuthUser(r).id);return this.db.modelVersion.findMany({where:{projectId:id},orderBy:{createdAt:'desc'}})}
 @Post(':id/duplicate') async duplicate(@Req()r:AuthRequest,@Param('id')id:string){const user=requireAuthUser(r),source=await this.db.project.findFirst({where:{id,userId:user.id},include:{versions:{orderBy:{createdAt:'desc'}}}});if(!source)throw new NotFoundException('Project not found.');return this.db.$transaction(async tx=>{const copy=await tx.project.create({data:{userId:user.id,modelAssetId:source.modelAssetId,name:`${source.name} Copy`}});const versions=[];for(const version of source.versions)versions.push(await tx.modelVersion.create({data:{projectId:copy.id,name:version.name,configurationJson:version.configurationJson as Prisma.InputJsonValue,previewUrl:version.previewUrl}}));if(versions.length)await tx.project.update({where:{id:copy.id},data:{activeVersionId:versions[0].id}});return tx.project.findUniqueOrThrow({where:{id:copy.id},include:{versions:true}})})}
 @Post(':id/export') async export(@Req()r:AuthRequest,@Param('id')id:string,@Body()body:{versionId?:string;configurationJson?:unknown}){const user=requireAuthUser(r),project=await this.db.project.findFirst({where:{id,userId:user.id},include:{modelAsset:{include:{manifests:{orderBy:{version:'desc'},take:1}}}}});if(!project)throw new NotFoundException('Project not found.');if(!project.modelAsset.sourceObjectKey)throw new BadRequestException('Project asset has no source object.');const manifestRecord=project.modelAsset.manifests[0];if(!manifestRecord)throw new BadRequestException('Project asset has no saved manifest.');const manifest=ModelManifestSchema.parse(manifestRecord.manifestJson);let rawConfig=body.configurationJson;if(body.versionId){const version=await this.db.modelVersion.findFirst({where:{id:body.versionId,projectId:id}});if(!version)throw new NotFoundException('Version not found.');rawConfig=version.configurationJson}if(!rawConfig&&project.activeVersionId){const version=await this.db.modelVersion.findFirst({where:{id:project.activeVersionId,projectId:id}});rawConfig=version?.configurationJson}const configuration=ModelConfigurationSchema.safeParse(rawConfig);if(!configuration.success)throw new BadRequestException('Provide a valid configuration or saved version.');const dbJob=await this.db.job.create({data:{type:'GLB_EXPORT',status:'QUEUED',modelAssetId:project.modelAssetId,payload:{projectId:id,userId:user.id,versionId:body.versionId??null}}});try{const queued=await this.exports.enqueue({databaseJobId:dbJob.id,projectId:id,assetId:project.modelAssetId,sourceObjectKey:project.modelAsset.sourceObjectKey,manifest,configuration:configuration.data,filename:`${project.name.replace(/[^a-zA-Z0-9_-]+/g,'_')||'product'}.glb`});await this.db.job.update({where:{id:dbJob.id},data:{bullmqJobId:String(queued.id)}});return{jobId:dbJob.id,status:'QUEUED'}}catch(error){await this.db.job.update({where:{id:dbJob.id},data:{status:'FAILED',failureReason:error instanceof Error?error.message:String(error)}});throw error}}
}
