import {BadRequestException,Body,Controller,Delete,Get,NotFoundException,Param,Post,Query,Req,UseGuards} from '@nestjs/common';import {PresetRuleSetSchema} from '@product3d/preset-engine';import {Prisma} from '@prisma/client';import {AuthRequest,requireAuthUser,SupabaseAuthGuard} from '../auth/auth.service';import {PrismaService} from '../prisma/prisma.service';import {StorageService} from '../storage/storage.service';function objectKey(uri:string){return /^supabase:\/\/[^/]+\/(.+)$/.exec(uri)?.[1]}
@Controller()
export class CatalogController{constructor(private readonly db:PrismaService,private readonly storage:StorageService){}
 @Get('variants') async variants(@Query('groupId')groupId?:string,@Query('role')role?:string){const rows=await this.db.componentVariant.findMany({where:{active:true,groupId:groupId||undefined,role:role||undefined}});return Promise.all(rows.map(async row=>{const metadata=row.metadataJson as Record<string,unknown>,compatibility=(row.compatibilityJson??{}) as{roles?:unknown;modelTags?:unknown},key=objectKey(row.assetUrl),roles=Array.isArray(compatibility.roles)?compatibility.roles.filter((item):item is string=>typeof item==='string'):[row.role],modelTags=Array.isArray(compatibility.modelTags)?compatibility.modelTags.filter((item):item is string=>typeof item==='string'):[];return{id:row.id,groupId:row.groupId,name:row.name,role:row.role,assetUrl:row.assetUrl,signedUrl:key?await this.storage.createDownloadUrl(key,900):row.assetUrl,anchorType:typeof metadata.anchorType==='string'?metadata.anchorType:'BOUNDS_CENTER',dimensionPolicy:metadata.dimensionPolicy==='KEEP'||metadata.dimensionPolicy==='RULE_BASED'?metadata.dimensionPolicy:'AUTO_FIT',compatibleModelTags:modelTags,compatibleComponentRoles:roles,metadata}}))}
 @Get('styles') styles(){return this.db.stylePreset.findMany({where:{active:true},orderBy:{name:'asc'}})}
 @Get('presets') @UseGuards(SupabaseAuthGuard) presets(@Req()r:AuthRequest){return this.db.userPreset.findMany({where:{userId:requireAuthUser(r).id},orderBy:{updatedAt:'desc'}})}
 @Post('presets') @UseGuards(SupabaseAuthGuard) async savePreset(@Req()r:AuthRequest,@Body()body:{name:string;rulesJson:unknown}){const rules=PresetRuleSetSchema.safeParse(body.rulesJson);if(!rules.success)throw new BadRequestException(rules.error.flatten());return this.db.userPreset.create({data:{userId:requireAuthUser(r).id,name:body.name,rulesJson:rules.data as Prisma.InputJsonValue}})}
 @Delete('presets/:id') @UseGuards(SupabaseAuthGuard) async removePreset(@Req()r:AuthRequest,@Param('id')id:string){const row=await this.db.userPreset.findFirst({where:{id,userId:requireAuthUser(r).id}});if(!row)throw new NotFoundException('Preset not found.');await this.db.userPreset.delete({where:{id}});return{deleted:true}}
}
