import {execFile} from 'node:child_process';
import {mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {promisify} from 'node:util';
import {Accessor,Document,Material,MathUtils,Mesh,Node,NodeIO,Primitive} from '@gltf-transform/core';
import {ALL_EXTENSIONS} from '@gltf-transform/extensions';
import {mergeDocuments} from '@gltf-transform/functions';
import {Prisma,PrismaClient} from '@prisma/client';
import {analyzeTriangleTopology,type TriangleRegion} from '@product3d/geometry-topology';
import type {ComponentManifest,ModelConfiguration,ModelManifest} from '@product3d/model-schema';
import {createClient} from '@supabase/supabase-js';
import {Job as BullJob,Worker} from 'bullmq';
import * as draco3d from 'draco3dgltf';
import {MeshoptDecoder,MeshoptEncoder} from 'meshoptimizer';
import validator from 'gltf-validator';

const QUEUE='export-processing';
const db=new PrismaClient();
const execFileAsync=promisify(execFile);
const workerDir=dirname(fileURLToPath(import.meta.url));
type ExportFormat='GLB'|'OBJ'|'STL';
type Data={databaseJobId:string;projectId:string;assetId:string;sourceObjectKey:string;manifest:ModelManifest;configuration:ModelConfiguration;filename:string;format:ExportFormat};
type VariantRecord={id:string;name:string;assetUrl:string;metadataJson:Prisma.JsonValue};
type VariantMetadata={dimensionPolicy?:'KEEP'|'AUTO_FIT'|'RULE_BASED';sourceDimensionsMm?:{width:number;height:number;depth:number}};
type ComponentSource={node:number;mesh:number;primitive:number;region?:number};
type PreparedTarget={node:Node;primitive?:Primitive;baseTranslation:[number,number,number];baseRotation:[number,number,number];baseScale:[number,number,number]};
type NumericArray=Int8Array|Uint8Array|Int16Array|Uint16Array|Uint32Array|Float32Array;

function env(name:string,fallback?:string){const value=process.env[name]??fallback;if(!value)throw new Error(`Missing ${name}`);return value;}
const bucket=env('SUPABASE_STORAGE_BUCKET','product3d');
const storage=createClient(env('SUPABASE_URL'),env('SUPABASE_SECRET_KEY'),{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
function redis(){const url=new URL(process.env.REDIS_URL??'redis://localhost:6379');return{host:url.hostname,port:Number(url.port||6379),username:url.username||undefined,password:url.password||undefined,db:url.pathname.length>1?Number(url.pathname.slice(1)):0,tls:url.protocol==='rediss:'?{}:undefined,maxRetriesPerRequest:null};}
async function io(){await Promise.all([MeshoptDecoder.ready,MeshoptEncoder.ready]);const[decoder,encoder]=await Promise.all([draco3d.createDecoderModule(),draco3d.createEncoderModule()]);return new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'draco3d.decoder':decoder,'draco3d.encoder':encoder,'meshopt.decoder':MeshoptDecoder,'meshopt.encoder':MeshoptEncoder});}

function parseComponentId(id:string):ComponentSource{const match=/^cmp_node_(\d+)_mesh_(\d+)_prim_(\d+)(?:_region_(\d+))?$/.exec(id);if(!match)throw new Error(`EXPORT_UNSTABLE_COMPONENT_ID: ${id}`);return{node:Number(match[1]),mesh:Number(match[2]),primitive:Number(match[3]),region:match[4]===undefined?undefined:Number(match[4])};}
function componentSource(definition:ComponentManifest):ComponentSource{const parsed=parseComponentId(definition.id);if(parsed.region!==undefined)return parsed;const regionId=definition.sourceRegionIds?.[0];const regionMatch=regionId?/_island_(\d+)$/.exec(regionId):null;return regionMatch?{...parsed,region:Number(regionMatch[1])}:parsed;}
function eulerToQuat([x,y,z]:[number,number,number]):[number,number,number,number]{const c1=Math.cos(x/2),c2=Math.cos(y/2),c3=Math.cos(z/2),s1=Math.sin(x/2),s2=Math.sin(y/2),s3=Math.sin(z/2);return[s1*c2*c3+c1*s2*s3,c1*s2*c3-s1*c2*s3,c1*c2*s3+s1*s2*c3,c1*c2*c3-s1*s2*s3];}
function quatToEuler([x,y,z,w]:number[]):[number,number,number]{const t0=2*(w*x+y*z),t1=1-2*(x*x+y*y),roll=Math.atan2(t0,t1),t2=Math.max(-1,Math.min(1,2*(w*y-z*x))),pitch=Math.asin(t2),t3=2*(w*z+x*y),t4=1-2*(y*y+z*z),yaw=Math.atan2(t3,t4);return[roll,pitch,yaw];}
function hex(value:string):[number,number,number,number]{const normalized=value.replace('#','');if(!/^[0-9a-fA-F]{6}$/.test(normalized))throw new Error(`Invalid color ${value}`);return[parseInt(normalized.slice(0,2),16)/255,parseInt(normalized.slice(2,4),16)/255,parseInt(normalized.slice(4,6),16)/255,1];}
function clonePrimitive(doc:Document,source:Primitive){return doc.createPrimitive().copy(source);}
function isolatedMesh(doc:Document,nodeIndex:number){const node=doc.getRoot().listNodes()[nodeIndex];if(!node)throw new Error(`Source node ${nodeIndex} missing`);const original=node.getMesh();if(!original)throw new Error(`Source node ${nodeIndex} has no mesh`);const mesh=doc.createMesh(`${original.getName()} Export`).copy(original);mesh.listPrimitives().forEach(primitive=>primitive.dispose());original.listPrimitives().forEach(primitive=>mesh.addPrimitive(clonePrimitive(doc,primitive)));node.setMesh(mesh);return mesh;}
function materialFor(doc:Document,primitive:Primitive,name:string){const original=primitive.getMaterial();const material=doc.createMaterial(name);if(original)material.copy(original);return material;}
function applyMaterial(material:Material,preset:Awaited<ReturnType<typeof db.materialPreset.findMany>>[number]|undefined,color?:string){if(preset){const properties=preset.propertiesJson as Record<string,unknown>;if(typeof properties.baseColor==='string')material.setBaseColorFactor(hex(properties.baseColor));if(typeof properties.roughness==='number')material.setRoughnessFactor(properties.roughness);if(typeof properties.metalness==='number')material.setMetallicFactor(properties.metalness);}if(color)material.setBaseColorFactor(hex(color));}
function applyNodeMaterials(doc:Document,root:Node,preset:Awaited<ReturnType<typeof db.materialPreset.findMany>>[number]|undefined,color?:string){const visit=(node:Node)=>{const mesh=node.getMesh();if(mesh)for(const primitive of mesh.listPrimitives()){if(!preset&&!color)continue;const material=materialFor(doc,primitive,`${node.getName()||'Variant'} Customized`);applyMaterial(material,preset,color);primitive.setMaterial(material);}for(const child of node.listChildren())visit(child);};visit(root);}
function variantObjectKey(uri:string){const match=/^supabase:\/\/([^/]+)\/(.+)$/.exec(uri);if(!match)throw new Error(`VARIANT_ASSET_URL_UNSUPPORTED: ${uri}`);if(match[1]!==bucket)throw new Error(`VARIANT_BUCKET_MISMATCH: ${match[1]}`);return match[2];}
function variantScale(metadata:VariantMetadata,state:ModelConfiguration['components'][string]):[number,number,number]{const policy=metadata.dimensionPolicy??'AUTO_FIT';if(policy==='KEEP')return[...state.transform.scale];const source=metadata.sourceDimensionsMm;if(!source||source.width<=0||source.height<=0||source.depth<=0)throw new Error('VARIANT_SOURCE_DIMENSIONS_REQUIRED');return[state.dimensionsMm.width/source.width*state.transform.scale[0],state.dimensionsMm.height/source.height*state.transform.scale[1],state.dimensionsMm.depth/source.depth*state.transform.scale[2]];}
async function loadVariantDocument(nodeIo:NodeIO,variant:VariantRecord){const objectKey=variantObjectKey(variant.assetUrl);const download=await storage.storage.from(bucket).download(objectKey);if(download.error||!download.data)throw download.error??new Error(`Variant asset ${variant.id} missing`);return nodeIo.readBinary(new Uint8Array(await download.data.arrayBuffer()));}
async function compositeVariant(doc:Document,nodeIo:NodeIO,node:Node,variant:VariantRecord,state:ModelConfiguration['components'][string],preset:Awaited<ReturnType<typeof db.materialPreset.findMany>>[number]|undefined,color?:string){const parent=node.getParentNode();const rootScenes=doc.getRoot().listScenes().filter(scene=>scene.listChildren().includes(node));const translation=node.getTranslation(),baseEuler=quatToEuler(node.getRotation());const beforeSceneCount=doc.getRoot().listScenes().length;const variantDoc=await loadVariantDocument(nodeIo,variant);mergeDocuments(doc,variantDoc);const mergedScenes=doc.getRoot().listScenes().slice(beforeSceneCount);if(!mergedScenes.length)throw new Error(`VARIANT_SCENE_MISSING: ${variant.id}`);const wrapper=doc.createNode(`Variant ${variant.name}`).setTranslation([translation[0]+state.transform.position[0]/1000,translation[1]+state.transform.position[1]/1000,translation[2]+state.transform.position[2]/1000]).setRotation(eulerToQuat([baseEuler[0]+state.transform.rotation[0],baseEuler[1]+state.transform.rotation[1],baseEuler[2]+state.transform.rotation[2]])).setScale(variantScale(variant.metadataJson as VariantMetadata,state));for(const scene of mergedScenes){for(const child of [...scene.listChildren()]){scene.removeChild(child);wrapper.addChild(child);}scene.dispose();}applyNodeMaterials(doc,wrapper,preset,color);if(parent)parent.addChild(wrapper);else(rootScenes[0]??doc.getRoot().getDefaultScene()??doc.createScene('Export Scene')).addChild(wrapper);node.dispose();}

function arrayConstructor(source:NumericArray){return source.constructor as{new(length:number):NumericArray};}
function copySubsetAttribute(doc:Document,source:Accessor,vertexIndices:number[],center:[number,number,number]|undefined,semantic:string){const sourceArray=source.getArray() as NumericArray|null;if(!sourceArray)throw new Error(`REGION_ATTRIBUTE_ARRAY_MISSING: ${semantic}`);const elementSize=source.getElementSize();let destination:NumericArray;if(semantic==='POSITION'&&center){destination=new Float32Array(vertexIndices.length*elementSize);for(let newIndex=0;newIndex<vertexIndices.length;newIndex++){const oldIndex=vertexIndices[newIndex];for(let component=0;component<elementSize;component++){const raw=Number(sourceArray[oldIndex*elementSize+component]);const decoded=source.getNormalized()?MathUtils.decodeNormalizedInt(raw,source.getComponentType()):raw;destination[newIndex*elementSize+component]=component<3?decoded-center[component]:decoded;}}}else{const Constructor=arrayConstructor(sourceArray);destination=new Constructor(vertexIndices.length*elementSize);for(let newIndex=0;newIndex<vertexIndices.length;newIndex++){const oldIndex=vertexIndices[newIndex];for(let component=0;component<elementSize;component++)destination[newIndex*elementSize+component]=sourceArray[oldIndex*elementSize+component] as never;}}return doc.createAccessor(source.getName()).setArray(destination).setType(source.getType()).setBuffer(doc.getRoot().listBuffers()[0]??doc.createBuffer()).setNormalized(semantic==='POSITION'&&center?false:source.getNormalized());}
function topologyForPrimitive(primitive:Primitive){const position=primitive.getAttribute('POSITION');if(!position?.getArray())throw new Error('REGION_POSITION_REQUIRED');if(primitive.listTargets().length)throw new Error('REGION_MORPH_TARGET_UNSUPPORTED');return analyzeTriangleTopology({positions:position.getArray()!,positionStride:position.getElementSize(),indices:primitive.getIndices()?.getArray()??null});}
function createRegionPrimitive(doc:Document,source:Primitive,region:TriangleRegion){const center:[number,number,number]=[(region.bounds.min[0]+region.bounds.max[0])/2,(region.bounds.min[1]+region.bounds.max[1])/2,(region.bounds.min[2]+region.bounds.max[2])/2];const primitive=doc.createPrimitive().setMode(source.getMode()).setMaterial(source.getMaterial()).setExtras(source.getExtras());for(const semantic of source.listSemantics()){const attribute=source.getAttribute(semantic);if(attribute)primitive.setAttribute(semantic,copySubsetAttribute(doc,attribute,region.vertexIndices,center,semantic));}const sourceIndices=source.getIndices();const remapped=new Map(region.vertexIndices.map((oldIndex,newIndex)=>[oldIndex,newIndex]));const values:number[]=[];for(const triangle of region.triangleIndices){for(let corner=0;corner<3;corner++){const oldIndex=sourceIndices?Number(sourceIndices.getArray()![triangle*3+corner]):triangle*3+corner;const value=remapped.get(oldIndex);if(value===undefined)throw new Error(`REGION_INDEX_MAPPING_MISSING: ${oldIndex}`);values.push(value);}}const ArrayType=region.vertexIndices.length>65535?Uint32Array:Uint16Array;const indices=doc.createAccessor().setArray(new ArrayType(values)).setType('SCALAR').setBuffer(doc.getRoot().listBuffers()[0]??doc.createBuffer());primitive.setIndices(indices);return{primitive,center};}

function componentGroups(manifest:ModelManifest){const groups=new Map<number,Array<{definition:ComponentManifest;source:ComponentSource}>>();for(const definition of manifest.components){const source=componentSource(definition);const list=groups.get(source.node)??[];list.push({definition,source});groups.set(source.node,list);}return groups;}
function prepareComponentTargets(doc:Document,manifest:ModelManifest){const targets=new Map<string,PreparedTarget>();for(const[nodeIndex,entries]of componentGroups(manifest)){const sourceNode=doc.getRoot().listNodes()[nodeIndex];if(!sourceNode)throw new Error(`Source node ${nodeIndex} missing`);const mustSplit=entries.length>1||entries.some(entry=>entry.source.region!==undefined);if(!mustSplit){const entry=entries[0];const mesh=isolatedMesh(doc,nodeIndex);const primitive=mesh.listPrimitives()[entry.source.primitive];if(!primitive)throw new Error(`Source primitive ${entry.source.primitive} missing for ${entry.definition.id}`);targets.set(entry.definition.id,{node:sourceNode,primitive,baseTranslation:[...sourceNode.getTranslation()],baseRotation:quatToEuler(sourceNode.getRotation()),baseScale:[...sourceNode.getScale()]});continue;}const isolated=isolatedMesh(doc,nodeIndex);const sourcePrimitives=[...isolated.listPrimitives()];const entriesByPrimitive=new Map<number,typeof entries>();for(const entry of entries){const list=entriesByPrimitive.get(entry.source.primitive)??[];list.push(entry);entriesByPrimitive.set(entry.source.primitive,list);}for(const[primitiveIndex,primitiveEntries]of entriesByPrimitive){const sourcePrimitive=sourcePrimitives[primitiveIndex];if(!sourcePrimitive)throw new Error(`Source primitive ${primitiveIndex} missing on node ${nodeIndex}`);const topology=primitiveEntries.some(entry=>entry.source.region!==undefined)?topologyForPrimitive(sourcePrimitive):undefined;for(const entry of primitiveEntries){let primitive:Primitive;let translation:[number,number,number]=[0,0,0];if(entry.source.region!==undefined){const region=topology?.regions[entry.source.region];if(!region)throw new Error(`REGION_NOT_FOUND: ${entry.definition.id}`);const extracted=createRegionPrimitive(doc,sourcePrimitive,region);primitive=extracted.primitive;translation=extracted.center;}else primitive=clonePrimitive(doc,sourcePrimitive);const mesh=doc.createMesh(`${entry.definition.name} Export`).addPrimitive(primitive);const child=doc.createNode(`${entry.definition.name} Export`).setMesh(mesh).setTranslation(translation);sourceNode.addChild(child);targets.set(entry.definition.id,{node:child,primitive,baseTranslation:translation,baseRotation:[0,0,0],baseScale:[1,1,1]});}sourcePrimitive.dispose();}if(isolated.listPrimitives().length===0)sourceNode.setMesh(null);}return targets;}

function applyTargetTransform(target:PreparedTarget,manifest:ModelManifest,state:ModelConfiguration['components'][string]){const ratios={x:1,y:1,z:1};for(const dimension of ['width','height','depth'] as const){const axis=manifest.axisMapping[dimension],original=state.originalDimensionsMm[dimension];ratios[axis]=original===0?1:state.dimensionsMm[dimension]/original;}target.node.setScale([target.baseScale[0]*ratios.x*state.transform.scale[0],target.baseScale[1]*ratios.y*state.transform.scale[1],target.baseScale[2]*ratios.z*state.transform.scale[2]]);target.node.setTranslation([target.baseTranslation[0]+state.transform.position[0]/1000,target.baseTranslation[1]+state.transform.position[1]/1000,target.baseTranslation[2]+state.transform.position[2]/1000]);target.node.setRotation(eulerToQuat([target.baseRotation[0]+state.transform.rotation[0],target.baseRotation[1]+state.transform.rotation[1],target.baseRotation[2]+state.transform.rotation[2]]));}
function applyPlacement(doc:Document,config:ModelConfiguration){const placement=config.placement.transform;if(placement.position.every(value=>value===0)&&placement.rotation.every(value=>value===0)&&placement.scale.every(value=>value===1))return;for(const scene of doc.getRoot().listScenes()){const wrapper=doc.createNode('Product Placement').setTranslation(placement.position).setRotation(eulerToQuat(placement.rotation)).setScale(placement.scale);for(const child of [...scene.listChildren()]){scene.removeChild(child);wrapper.addChild(child);}scene.addChild(wrapper);}}

async function bake(doc:Document,nodeIo:NodeIO,manifest:ModelManifest,config:ModelConfiguration){const materialIds=[...new Set(Object.values(config.components).map(component=>component.materialId).filter((value):value is string=>Boolean(value)))],variantIds=[...new Set(Object.values(config.components).map(component=>component.variantId).filter((value):value is string=>Boolean(value)))];const[presets,variants]=await Promise.all([materialIds.length?db.materialPreset.findMany({where:{id:{in:materialIds}}}):Promise.resolve([]),variantIds.length?db.componentVariant.findMany({where:{id:{in:variantIds},active:true},select:{id:true,name:true,assetUrl:true,metadataJson:true}}):Promise.resolve([])]);const presetMap=new Map(presets.map(preset=>[preset.id,preset])),variantMap=new Map(variants.map(variant=>[variant.id,variant]));const targets=prepareComponentTargets(doc,manifest);for(const definition of manifest.components){const state=config.components[definition.id];if(!state)continue;const target=targets.get(definition.id);if(!target)throw new Error(`EXPORT_COMPONENT_TARGET_MISSING: ${definition.id}`);if(state.deleted||!state.visible){target.node.dispose();continue;}const preset=state.materialId?presetMap.get(state.materialId):undefined;if(state.variantId){const variant=variantMap.get(state.variantId);if(!variant)throw new Error(`VARIANT_NOT_FOUND: ${state.variantId}`);await compositeVariant(doc,nodeIo,target.node,variant,state,preset,state.color);continue;}applyTargetTransform(target,manifest,state);if((state.materialId||state.color)&&target.primitive){const material=materialFor(doc,target.primitive,`${definition.name} Customized`);applyMaterial(material,preset,state.color);target.primitive.setMaterial(material);}}applyPlacement(doc,config);}

async function convertDerived(glb:Uint8Array,format:Exclude<ExportFormat,'GLB'>){const dir=await mkdtemp(join(tmpdir(),'product3d-export-'));try{const input=join(dir,'customized.glb'),output=join(dir,`customized.${format.toLowerCase()}`);await writeFile(input,glb);const script=join(workerDir,'../convert.py');await execFileAsync(process.env.PYTHON_BIN??'python3',[script,input,output,format.toLowerCase()],{timeout:Number(process.env.FORMAT_EXPORT_TIMEOUT_MS??120000),maxBuffer:1024*1024});return new Uint8Array(await readFile(output));}finally{await rm(dir,{recursive:true,force:true});}}
function contentType(format:ExportFormat){if(format==='GLB')return'model/gltf-binary';if(format==='STL')return'model/stl';return'text/plain; charset=utf-8';}
async function processJob(job:BullJob<Data>){const data=job.data;await db.job.update({where:{id:data.databaseJobId},data:{status:'PROCESSING',failureReason:null}});try{const download=await storage.storage.from(bucket).download(data.sourceObjectKey);if(download.error||!download.data)throw download.error??new Error('Source object missing');const source=new Uint8Array(await download.data.arrayBuffer());const nodeIo=await io();const document=await nodeIo.readBinary(source);await bake(document,nodeIo,data.manifest,data.configuration);const glb=await nodeIo.writeBinary(document);const report=await validator.validateBytes(glb,{uri:data.format==='GLB'?data.filename:'customized.glb',format:'glb',maxIssues:5000});if(report.issues.numErrors)throw new Error(`Export validation failed with ${report.issues.numErrors} error(s)`);const output=data.format==='GLB'?glb:await convertDerived(glb,data.format),objectKey=`exports/${data.projectId}/${data.databaseJobId}/${data.filename}`;const uploaded=await storage.storage.from(bucket).upload(objectKey,output,{contentType:contentType(data.format),upsert:false});if(uploaded.error)throw uploaded.error;const result:Prisma.InputJsonObject={objectKey,filename:data.filename,format:data.format,sizeBytes:output.byteLength,sourceGlbValidation:{errors:report.issues.numErrors,warnings:report.issues.numWarnings},unit:data.format==='GLB'?'meter':'millimeter'};await db.job.update({where:{id:data.databaseJobId},data:{status:'COMPLETED',result}});return result;}catch(error){const message=error instanceof Error?error.message:String(error),retry=job.attemptsMade+1<(job.opts.attempts??1);await db.job.update({where:{id:data.databaseJobId},data:{status:retry?'RETRYING':'FAILED',failureReason:message}});throw error;}}
const worker=new Worker<Data>(QUEUE,processJob,{connection:redis(),concurrency:Number(process.env.EXPORT_WORKER_CONCURRENCY??2)});worker.on('completed',job=>console.info(`[export-worker] completed ${job.id}`));worker.on('failed',(job,error)=>console.error(`[export-worker] failed ${job?.id??'unknown'}: ${error.message}`));async function shutdown(){await worker.close();await db.$disconnect();process.exit(0);}process.on('SIGINT',()=>void shutdown());process.on('SIGTERM',()=>void shutdown());console.info(`[export-worker] listening on ${QUEUE}`);
