import {describe,expect,it} from 'vitest';
import {applyAction} from '../packages/editor-core/src/index';
import {
  ModelConfigurationSchema,
  ModelManifestSchema,
  type ModelConfiguration,
  type ModelManifest,
  type TransformState,
} from '../packages/model-schema/src/index';

const transform=(position:[number,number,number]=[0,0,0]):TransformState=>({position:[...position],rotation:[0,0,0],scale:[1,1,1]});
const component=(id:string)=>({
  id,sourceNodeIds:[`node_${id}`],sourceMeshIds:[`mesh_${id}`],name:id,role:'OTHER' as const,
  editable:true,editableAxes:{x:true,y:true,z:true},scalingMode:'AXIS_SCALE' as const,
  constraints:{width:null,height:null,depth:null},anchorIds:[`${id}-anchor`],materialSlotIds:[],
});

function manifest(compatible=true):ModelManifest{
  return{
    modelId:'aircraft',version:1,unit:'mm',axisMapping:{width:'x',height:'y',depth:'z'},
    components:[component('wing'),component('body')],dependencies:[],
    anchors:[
      {
        id:'wing-anchor',componentId:'wing',name:'Wing root',kind:'PLANE',positionMm:[0,0,0],rotation:[0,0,0],tags:['WING_ROOT'],
        connectionType:'WING_ROOT',compatibleTypes:compatible?['WING_MOUNT']:['ENGINE_MOUNT'],autoGenerated:false,snapEnabled:true,alignRotation:true,
      },
      {
        id:'body-anchor',componentId:'body',name:'Wing mount',kind:'PLANE',positionMm:[0,0,0],rotation:[0,Math.PI,0],tags:['WING_MOUNT'],
        connectionType:'WING_MOUNT',compatibleTypes:['WING_ROOT'],autoGenerated:false,snapEnabled:true,alignRotation:true,
      },
    ],
  };
}

function config():ModelConfiguration{
  return{
    modelId:'aircraft',manifestVersion:1,placement:{locked:true,transform:transform()},attachments:[],
    components:{
      wing:{originalDimensionsMm:{width:100,height:20,depth:60},dimensionsMm:{width:100,height:20,depth:60},transform:transform(),visible:true,deleted:false},
      body:{originalDimensionsMm:{width:500,height:150,depth:120},dimensionsMm:{width:500,height:150,depth:120},transform:transform(),visible:true,deleted:false},
    },
  };
}

const attachAction={type:'ATTACH_COMPONENT',componentId:'wing',sourceAnchorId:'wing-anchor',targetComponentId:'body',targetAnchorId:'body-anchor',createdBy:'SNAP',source:'MANUAL'} as const;

describe('semantic anchor attachments',()=>{
  it('persists a compatible logical attachment without changing component hierarchy data',()=>{
    const result=applyAction(attachAction,manifest(),config());
    expect(result.ok).toBe(true);
    if(!result.ok)return;
    expect(result.configuration.attachments).toHaveLength(1);
    expect(result.configuration.attachments?.[0]).toMatchObject({sourceComponentId:'wing',targetComponentId:'body',sourceAnchorId:'wing-anchor',targetAnchorId:'body-anchor'});
    expect(result.configuration.components.wing.transform.position).toEqual([0,0,0]);
    expect(result.configuration.components.body.transform.position).toEqual([0,0,0]);
  });

  it('rejects semantic anchor types that are not mutually compatible',()=>{
    const result=applyAction(attachAction,manifest(false),config());
    expect(result.ok).toBe(false);
    if(result.ok)return;
    expect(result.code).toBe('ANCHOR_INCOMPATIBLE');
  });

  it('moves attached sources when their target translates',()=>{
    const attached=applyAction(attachAction,manifest(),config());
    expect(attached.ok).toBe(true);
    if(!attached.ok)return;
    const moved=applyAction({type:'SET_POSITION',componentId:'body',axis:'X',value:240,source:'MANUAL'},manifest(),attached.configuration);
    expect(moved.ok).toBe(true);
    if(!moved.ok)return;
    expect(moved.configuration.components.body.transform.position[0]).toBe(240);
    expect(moved.configuration.components.wing.transform.position[0]).toBe(240);
    expect(moved.configuration.attachments).toHaveLength(1);
  });

  it('detaches a source when the user deliberately moves it away',()=>{
    const attached=applyAction(attachAction,manifest(),config());
    expect(attached.ok).toBe(true);
    if(!attached.ok)return;
    const moved=applyAction({type:'SET_POSITION',componentId:'wing',axis:'Z',value:75,source:'MANUAL'},manifest(),attached.configuration);
    expect(moved.ok).toBe(true);
    if(!moved.ok)return;
    expect(moved.configuration.components.wing.transform.position[2]).toBe(75);
    expect(moved.configuration.attachments).toEqual([]);
  });

  it('parses legacy manifests and configurations that predate anchors and attachments',()=>{
    const oldManifest={...manifest()};delete (oldManifest as Partial<ModelManifest>).anchors;
    const oldConfig={...config()};delete (oldConfig as Partial<ModelConfiguration>).attachments;
    expect(ModelManifestSchema.safeParse(oldManifest).success).toBe(true);
    expect(ModelConfigurationSchema.safeParse(oldConfig).success).toBe(true);
  });
});
