import {describe,expect,it} from 'vitest';
import {EditorActionSchema} from '../packages/action-engine/src/index';
import {canApplyMaterial,canApplyVariant} from '../packages/compatibility-engine/src/index';
import {fromMm,toMm,validateAction} from '../packages/constraint-engine/src/index';
import {applyAction,applyActions} from '../packages/editor-core/src/index';
import {ModelConfigurationSchema,type ComponentVariant,type MaterialPreset,type ModelConfiguration,type ModelManifest} from '../packages/model-schema/src/index';

const manifest:ModelManifest={modelId:'m1',version:1,unit:'mm',axisMapping:{width:'x',height:'y',depth:'z'},components:[{id:'top',sourceNodeIds:['node_0000'],sourceMeshIds:['mesh_0000'],name:'Top',role:'TOP',editable:true,editableAxes:{x:true,y:false,z:true},scalingMode:'AXIS_SCALE',constraints:{width:{min:400,max:800},height:null,depth:{min:300,max:700}},anchorIds:[],variantGroupId:'tops',allowedMaterialCategories:['WOOD'],materialSlotIds:[]},{id:'leg',sourceNodeIds:['node_0001'],sourceMeshIds:['mesh_0001'],name:'Leg',role:'LEG',editable:true,editableAxes:{x:false,y:true,z:false},scalingMode:'AXIS_SCALE',constraints:{width:null,height:{min:400,max:900},depth:null},anchorIds:[],materialSlotIds:[]}],dependencies:[{id:'d1',sourceComponentId:'top',triggerProperty:'WIDTH',targetComponentId:'leg',targetProperty:'POSITION_X',formula:{type:'DELTA_FACTOR',factor:.5}}]};
const config:ModelConfiguration={modelId:'m1',manifestVersion:1,placement:{locked:true,transform:{position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]}},components:{top:{originalDimensionsMm:{width:600,height:40,depth:500},dimensionsMm:{width:600,height:40,depth:500},transform:{position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]},visible:true,deleted:false},leg:{originalDimensionsMm:{width:50,height:700,depth:50},dimensionsMm:{width:50,height:700,depth:50},transform:{position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]},visible:true,deleted:false}}};
const oak:MaterialPreset={id:'oak',name:'Oak',category:'WOOD',roughness:.6,metalness:0,styleTags:[],allowColorTint:true};
const fabric:MaterialPreset={id:'fabric',name:'Fabric',category:'FABRIC',roughness:.8,metalness:0,styleTags:[],allowColorTint:true};
const variant:ComponentVariant={id:'v1',groupId:'tops',name:'Top Variant',role:'TOP',assetUrl:'variant.glb',anchorType:'CENTER',compatibleModelTags:[],compatibleComponentRoles:['TOP'],dimensionPolicy:'AUTO_FIT'};

describe('action schema',()=>{it('rejects malformed color actions',()=>{expect(EditorActionSchema.safeParse({type:'SET_COLOR',componentId:'top',color:'red',source:'MANUAL'}).success).toBe(false);});});
describe('constraints and units',()=>{it('rejects dimensions above configured max',()=>{expect(validateAction({type:'SET_DIMENSION',componentId:'top',axis:'WIDTH',valueMm:900,source:'MANUAL'},manifest,config)).toMatchObject({ok:false,code:'ABOVE_MAX'});});it('requires placement lock',()=>{const unlocked=structuredClone(config);unlocked.placement.locked=false;expect(validateAction({type:'SET_DIMENSION',componentId:'top',axis:'WIDTH',valueMm:650,source:'MANUAL'},manifest,unlocked)).toMatchObject({ok:false,code:'PLACEMENT_NOT_LOCKED'});});it('converts mm/cm/inch without drift at known values',()=>{expect(toMm(2.54,'cm')).toBeCloseTo(25.4);expect(toMm(1,'inch')).toBeCloseTo(25.4);expect(fromMm(25.4,'inch')).toBeCloseTo(1);});});
describe('compatibility',()=>{it('allows only configured material categories',()=>{expect(canApplyMaterial(manifest.components[0],oak)).toBe(true);expect(canApplyMaterial(manifest.components[0],fabric)).toBe(false);});it('validates variant group and role',()=>{expect(canApplyVariant(manifest.components[0],variant)).toBe(true);expect(canApplyVariant(manifest.components[1],variant)).toBe(false);});});
describe('editor transaction and dependencies',()=>{it('resolves deterministic dependency after width delta',()=>{const result=applyAction({type:'SET_DIMENSION',componentId:'top',axis:'WIDTH',valueMm:700,source:'MANUAL'},manifest,config);expect(result.ok).toBe(true);if(result.ok)expect(result.configuration.components.leg.transform.position[0]).toBe(50);});it('does not mutate input when a batch contains an invalid action',()=>{const before=structuredClone(config);const result=applyActions([{type:'SET_DIMENSION',componentId:'top',axis:'WIDTH',valueMm:700,source:'STYLE'},{type:'SET_MATERIAL',componentId:'top',materialId:'fabric',source:'STYLE'}],manifest,config,{materials:[oak,fabric]});expect(result.ok).toBe(false);expect(config).toEqual(before);});});
describe('version serialization',()=>{it('round-trips configuration as serializable business state',()=>{const json=JSON.stringify(config);expect(ModelConfigurationSchema.parse(JSON.parse(json))).toEqual(config);});});
