import {describe,expect,it} from 'vitest';
import {canApplyVariant,findVariantPlacementAnchor,resolveVariantAnchorTransform} from '../packages/compatibility-engine/src/index';
import type {AnchorDefinition,ComponentManifest,ComponentVariant} from '../packages/model-schema/src/index';

const component:ComponentManifest={
  id:'wing',sourceNodeIds:[],sourceMeshIds:[],name:'Wing',role:'PANEL',editable:true,
  editableAxes:{x:true,y:true,z:true},scalingMode:'AXIS_SCALE',constraints:{width:null,height:null,depth:null},anchorIds:['center','mount'],materialSlotIds:[],variantGroupId:'wings',
};
const center:AnchorDefinition={id:'center',componentId:'wing',name:'Center',kind:'BOUNDS_CENTER',positionMm:[0,0,0],rotation:[0,0,0],tags:[],connectionType:'GENERIC',compatibleTypes:['GENERIC'],autoGenerated:true,status:'AUTO',confidence:.4,snapEnabled:true,alignRotation:false};
const mount:AnchorDefinition={id:'mount',componentId:'wing',name:'Wing mount',kind:'POINT',positionMm:[100,0,0],rotation:[0,0,Math.PI/2],tags:[],connectionType:'WING_MOUNT',compatibleTypes:['WING_ROOT'],autoGenerated:false,status:'CONFIRMED',confidence:1,snapEnabled:true,alignRotation:true};
function variant(patch:Partial<ComponentVariant>={}):ComponentVariant{return{id:'v1',groupId:'wings',name:'Alt Wing',role:'PANEL',assetUrl:'supabase://product3d/v.glb',anchorType:'BOUNDS_CENTER',compatibleModelTags:[],compatibleComponentRoles:['PANEL'],dimensionPolicy:'AUTO_FIT',...patch};}

describe('variant compatibility',()=>{
  it('uses the declared semantic anchor and prefers confirmed metadata',()=>{
    expect(findVariantPlacementAnchor(component,variant({anchorType:'WING_MOUNT'}),[center,mount])?.id).toBe('mount');
  });
  it('rejects semantic variants when the required anchor is absent',()=>{
    expect(canApplyVariant(component,variant({anchorType:'WING_MOUNT'}),[],[center])).toBe(false);
  });
  it('enforces model tags when a variant declares them',()=>{
    const tagged=variant({compatibleModelTags:['aircraft']});
    expect(canApplyVariant(component,tagged,['furniture'],[center,mount])).toBe(false);
    expect(canApplyVariant(component,tagged,['AIRCRAFT'],[center,mount])).toBe(true);
  });
  it('keeps BOUNDS_CENTER variants compatible without a semantic custom anchor',()=>{
    expect(canApplyVariant(component,variant(),[],[center])).toBe(true);
  });
  it('maps legacy CENTER to a neutral virtual bounds center when an old manifest has no anchors',()=>{
    const legacy=variant({anchorType:'CENTER'});
    expect(canApplyVariant(component,legacy,[],[])).toBe(true);
    const anchor=findVariantPlacementAnchor(component,legacy,[]);
    expect(anchor).toMatchObject({kind:'BOUNDS_CENTER',positionMm:[0,0,0],rotation:[0,0,0]});
  });
});

describe('variant anchor transform',()=>{
  it('transforms the anchor position by component scale and rotation',()=>{
    const resolved=resolveVariantAnchorTransform({translation:[1,2,3],rotation:[0,0,Math.SQRT1_2,Math.SQRT1_2],scale:[2,1,1],anchor:mount});
    expect(resolved.translation[0]).toBeCloseTo(1,6);
    expect(resolved.translation[1]).toBeCloseTo(2.2,6);
    expect(resolved.translation[2]).toBeCloseTo(3,6);
    // Base Z 90° plus anchor Z 90° => 180° around Z.
    expect(Math.abs(resolved.rotation[2])).toBeCloseTo(1,6);
    expect(Math.abs(resolved.rotation[3])).toBeCloseTo(0,6);
  });
});
