import {beforeEach,describe,expect,it} from 'vitest';
import type {AnchorDefinition,ModelConfiguration,ModelManifest} from '@product3d/model-schema';
import * as THREE from 'three';
import {findNearestAnchorCandidate,resetSnapCandidateMemory} from './anchor-runtime';

function component(id:string,name=id){
  return{id,name,sourceNodeIds:[],sourceMeshIds:[],role:'OTHER' as const,editable:true,editableAxes:{x:true,y:true,z:true},scalingMode:'AXIS_SCALE' as const,constraints:{width:null,height:null,depth:null},anchorIds:[],materialSlotIds:[]};
}

function state(){
  return{originalDimensionsMm:{width:1,height:1,depth:1},dimensionsMm:{width:1,height:1,depth:1},transform:{position:[0,0,0] as[number,number,number],rotation:[0,0,0] as[number,number,number],scale:[1,1,1] as[number,number,number]},visible:true,deleted:false};
}

function anchor(input:Partial<AnchorDefinition>&Pick<AnchorDefinition,'id'|'componentId'>):AnchorDefinition{
  return{
    name:input.id,
    kind:'POINT',
    positionMm:[0,0,0],
    rotation:[0,0,0],
    tags:[],
    connectionType:'GENERIC',
    compatibleTypes:['GENERIC'],
    autoGenerated:false,
    status:'CONFIRMED',
    confidence:1,
    snapEnabled:true,
    alignRotation:false,
    ...input,
  };
}

function setup(modelId:string,anchors:AnchorDefinition[]){
  const manifest={modelId,version:1,unit:'mm' as const,axisMapping:{width:'x' as const,height:'y' as const,depth:'z' as const},components:[component('source'),component('a','Target A'),component('b','Target B')],dependencies:[],anchors} satisfies ModelManifest;
  const configuration={modelId,manifestVersion:1,placement:{locked:true,transform:{position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]}},components:{source:state(),a:state(),b:state()},attachments:[]} satisfies ModelConfiguration;
  const source=new THREE.Object3D();
  const a=new THREE.Object3D();
  const b=new THREE.Object3D();
  const objects=new Map<string,THREE.Object3D>([['source',source],['a',a],['b',b]]);
  return{manifest,configuration,source,a,b,objects};
}

describe('snap candidate policy',()=>{
  beforeEach(()=>resetSnapCandidateMemory());

  it('prefers a compatible confirmed semantic anchor over a slightly closer generic/incompatible point',()=>{
    const sourceAnchor=anchor({id:'source-root',componentId:'source',connectionType:'WING_ROOT',compatibleTypes:['WING_MOUNT']});
    const generic=anchor({id:'a-generic',componentId:'a',connectionType:'GENERIC',compatibleTypes:['GENERIC'],autoGenerated:true,status:'AUTO',confidence:.5});
    const semantic=anchor({id:'b-mount',componentId:'b',connectionType:'WING_MOUNT',compatibleTypes:['WING_ROOT']});
    const env=setup('ranking',[sourceAnchor,generic,semantic]);
    env.a.position.x=.05;
    env.b.position.x=.07;
    const result=findNearestAnchorCandidate({sourceComponentId:'source',sourceObject:env.source,manifest:env.manifest,configuration:env.configuration,objects:env.objects});
    expect(result?.targetComponentId).toBe('b');
    expect(result?.compatible).toBe(true);
  });

  it('keeps the active candidate until another option becomes meaningfully better',()=>{
    const sourceAnchor=anchor({id:'source-generic',componentId:'source'});
    const aAnchor=anchor({id:'a-generic',componentId:'a'});
    const bAnchor=anchor({id:'b-generic',componentId:'b'});
    const env=setup('sticky',[sourceAnchor,aAnchor,bAnchor]);
    env.a.position.x=.05;
    env.b.position.x=.052;
    expect(findNearestAnchorCandidate({sourceComponentId:'source',sourceObject:env.source,manifest:env.manifest,configuration:env.configuration,objects:env.objects})?.targetComponentId).toBe('a');

    env.b.position.x=.04;
    expect(findNearestAnchorCandidate({sourceComponentId:'source',sourceObject:env.source,manifest:env.manifest,configuration:env.configuration,objects:env.objects})?.targetComponentId).toBe('a');

    env.b.position.x=.03;
    expect(findNearestAnchorCandidate({sourceComponentId:'source',sourceObject:env.source,manifest:env.manifest,configuration:env.configuration,objects:env.objects})?.targetComponentId).toBe('b');
  });
});
