import type { AnchorDefinition, ModelConfiguration, ModelManifest } from '@product3d/model-schema';
import * as THREE from 'three';
import { anchorCompatible, anchorsForComponent } from './snap';

export type RuntimeSnapCandidate = {
  sourceAnchor: AnchorDefinition;
  targetAnchor: AnchorDefinition;
  targetComponentId: string;
  targetComponentName: string;
  targetObject: THREE.Object3D;
  distanceWorld: number;
  compatible: boolean;
};

const FACE_ROTATIONS: Record<string, [number, number, number]> = {
  CENTER: [0,0,0],
  RIGHT: [0,Math.PI/2,0],
  LEFT: [0,-Math.PI/2,0],
  TOP: [-Math.PI/2,0,0],
  BOTTOM: [Math.PI/2,0,0],
  FRONT: [0,0,0],
  BACK: [0,Math.PI,0],
};

export function autoAnchorsForMesh(componentId:string,mesh:THREE.Mesh):AnchorDefinition[]{
  if(!mesh.geometry.boundingBox)mesh.geometry.computeBoundingBox();
  const box=mesh.geometry.boundingBox;
  if(!box||box.isEmpty())return[];
  const center=box.getCenter(new THREE.Vector3());
  const specs:[string,THREE.Vector3,'BOUNDS_CENTER'|'PLANE'][]=[
    ['CENTER',center.clone(),'BOUNDS_CENTER'],
    ['RIGHT',new THREE.Vector3(box.max.x,center.y,center.z),'PLANE'],
    ['LEFT',new THREE.Vector3(box.min.x,center.y,center.z),'PLANE'],
    ['TOP',new THREE.Vector3(center.x,box.max.y,center.z),'PLANE'],
    ['BOTTOM',new THREE.Vector3(center.x,box.min.y,center.z),'PLANE'],
    ['FRONT',new THREE.Vector3(center.x,center.y,box.max.z),'PLANE'],
    ['BACK',new THREE.Vector3(center.x,center.y,box.min.z),'PLANE'],
  ];
  return specs.map(([face,position,kind])=>({
    id:`${componentId}__auto_${face.toLowerCase()}`,
    componentId,
    name:`${face[0]}${face.slice(1).toLowerCase()}`,
    kind,
    positionMm:[position.x*1000,position.y*1000,position.z*1000],
    rotation:FACE_ROTATIONS[face],
    tags:['AUTO',face],
    connectionType:'GENERIC',
    compatibleTypes:['GENERIC'],
    autoGenerated:true,
    snapEnabled:true,
    alignRotation:false,
  }));
}

export function anchorWorldPosition(object:THREE.Object3D,anchor:AnchorDefinition){
  object.updateWorldMatrix(true,false);
  return new THREE.Vector3(...anchor.positionMm).multiplyScalar(.001).applyMatrix4(object.matrixWorld);
}

export function anchorWorldQuaternion(object:THREE.Object3D,anchor:AnchorDefinition){
  object.updateWorldMatrix(true,false);
  const objectWorld=object.getWorldQuaternion(new THREE.Quaternion());
  const local=new THREE.Quaternion().setFromEuler(new THREE.Euler(...anchor.rotation));
  return objectWorld.multiply(local);
}

export function findNearestAnchorCandidate({
  sourceComponentId,
  sourceObject,
  manifest,
  configuration,
  objects,
}:{
  sourceComponentId:string;
  sourceObject:THREE.Object3D;
  manifest:ModelManifest;
  configuration:ModelConfiguration;
  objects:Map<string,THREE.Object3D>;
}):RuntimeSnapCandidate|undefined{
  const anchors=manifest.anchors??[];
  const sourceAnchors=anchorsForComponent(anchors,sourceComponentId);
  if(!sourceAnchors.length)return undefined;
  let best:RuntimeSnapCandidate|undefined;
  for(const targetDefinition of manifest.components){
    if(targetDefinition.id===sourceComponentId)continue;
    const targetState=configuration.components[targetDefinition.id];
    const targetObject=objects.get(targetDefinition.id);
    if(!targetState||!targetObject||targetState.deleted||!targetState.visible)continue;
    const targetAnchors=anchorsForComponent(anchors,targetDefinition.id);
    for(const sourceAnchor of sourceAnchors){
      const sourcePosition=anchorWorldPosition(sourceObject,sourceAnchor);
      for(const targetAnchor of targetAnchors){
        const distanceWorld=sourcePosition.distanceTo(anchorWorldPosition(targetObject,targetAnchor));
        if(!best||distanceWorld<best.distanceWorld){
          best={
            sourceAnchor,
            targetAnchor,
            targetComponentId:targetDefinition.id,
            targetComponentName:targetDefinition.name,
            targetObject,
            distanceWorld,
            compatible:anchorCompatible(sourceAnchor,targetAnchor),
          };
        }
      }
    }
  }
  return best;
}

export function snappedLocalTransform(
  sourceObject:THREE.Object3D,
  sourceAnchor:AnchorDefinition,
  targetObject:THREE.Object3D,
  targetAnchor:AnchorDefinition,
){
  const parent=sourceObject.parent;
  const targetWorldPosition=anchorWorldPosition(targetObject,targetAnchor);
  const targetParentPosition=parent?parent.worldToLocal(targetWorldPosition.clone()):targetWorldPosition.clone();

  let localQuaternion=sourceObject.quaternion.clone();
  if(sourceAnchor.alignRotation&&targetAnchor.alignRotation){
    const desiredAnchorWorld=anchorWorldQuaternion(targetObject,targetAnchor)
      .multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),Math.PI));
    const sourceAnchorLocal=new THREE.Quaternion().setFromEuler(new THREE.Euler(...sourceAnchor.rotation));
    const desiredSourceWorld=desiredAnchorWorld.multiply(sourceAnchorLocal.invert());
    if(parent){
      const parentWorld=parent.getWorldQuaternion(new THREE.Quaternion());
      localQuaternion=parentWorld.invert().multiply(desiredSourceWorld);
    }else localQuaternion=desiredSourceWorld;
  }

  const anchorOffset=new THREE.Vector3(...sourceAnchor.positionMm)
    .multiplyScalar(.001)
    .multiply(sourceObject.scale)
    .applyQuaternion(localQuaternion);
  const position=targetParentPosition.sub(anchorOffset);
  const rotation=new THREE.Euler().setFromQuaternion(localQuaternion,sourceObject.rotation.order);
  return {position,rotation};
}
