import {beforeEach,describe,expect,it} from 'vitest';
import type {ModelConfiguration,ModelManifest} from '@product3d/model-schema';
import {useEditorStore} from './store';
import {useSnapInteractionStore} from './snap-store';

const manifest:ModelManifest={
  modelId:'snap-intent',version:1,unit:'mm',axisMapping:{width:'x',height:'y',depth:'z'},dependencies:[],
  components:[
    {id:'source',sourceNodeIds:[],sourceMeshIds:[],name:'Source',role:'OTHER',editable:true,editableAxes:{x:true,y:true,z:true},scalingMode:'AXIS_SCALE',constraints:{width:null,height:null,depth:null},anchorIds:['source-anchor'],materialSlotIds:[]},
    {id:'target',sourceNodeIds:[],sourceMeshIds:[],name:'Target',role:'OTHER',editable:true,editableAxes:{x:true,y:true,z:true},scalingMode:'AXIS_SCALE',constraints:{width:null,height:null,depth:null},anchorIds:['target-anchor'],materialSlotIds:[]},
  ],
  anchors:[
    {id:'source-anchor',componentId:'source',name:'Source',kind:'POINT',positionMm:[0,0,0],rotation:[0,0,0],tags:[],connectionType:'PLUG',compatibleTypes:['SOCKET'],autoGenerated:false,status:'CONFIRMED',confidence:1,snapEnabled:true,alignRotation:false},
    {id:'target-anchor',componentId:'target',name:'Target',kind:'POINT',positionMm:[0,0,0],rotation:[0,0,0],tags:[],connectionType:'SOCKET',compatibleTypes:['PLUG'],autoGenerated:false,status:'CONFIRMED',confidence:1,snapEnabled:true,alignRotation:false},
  ],
};

function componentState(){return{originalDimensionsMm:{width:100,height:100,depth:100},dimensionsMm:{width:100,height:100,depth:100},transform:{position:[0,0,0] as[number,number,number],rotation:[0,0,0] as[number,number,number],scale:[1,1,1] as[number,number,number]},visible:true,deleted:false};}
function configuration():ModelConfiguration{return{modelId:'snap-intent',manifestVersion:1,placement:{locked:true,transform:{position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]}},components:{source:componentState(),target:componentState()},attachments:[]};}

const actions=[
  {type:'SET_POSITION' as const,componentId:'source',axis:'X' as const,value:25,source:'MANUAL' as const},
  {type:'ATTACH_COMPONENT' as const,componentId:'source',sourceAnchorId:'source-anchor',targetComponentId:'target',targetAnchorId:'target-anchor',createdBy:'SNAP' as const,source:'MANUAL' as const},
];

describe('snap vs attach mutation intent',()=>{
  beforeEach(()=>{
    useEditorStore.setState({phase:'EDITOR',manifest,configuration:configuration(),selected:'source',undoStack:[],redoStack:[],error:undefined,variants:{}});
    useSnapInteractionStore.setState({snapEnabled:false,persistentSnapEnabled:false,temporarySnapActive:false,attachMode:false,candidate:undefined,groundBarrier:undefined});
  });

  it('commits snapped position without creating an attachment outside Attach mode',()=>{
    expect(useEditorStore.getState().dispatchBatch(actions,'Position snap')).toBe(true);
    expect(useEditorStore.getState().configuration?.components.source.transform.position[0]).toBe(25);
    expect(useEditorStore.getState().configuration?.attachments).toEqual([]);
  });

  it('creates the relationship only with explicit Attach mode and exits that mode after success',()=>{
    useSnapInteractionStore.getState().setAttachMode(true);
    expect(useEditorStore.getState().dispatchBatch(actions,'Attach snap')).toBe(true);
    expect(useEditorStore.getState().configuration?.attachments).toHaveLength(1);
    expect(useEditorStore.getState().configuration?.attachments?.[0].targetComponentId).toBe('target');
    expect(useSnapInteractionStore.getState().attachMode).toBe(false);
  });
});
