import type { AnchorDefinition,ComponentManifest,ComponentVariant,MaterialPreset } from '@product3d/model-schema';

type Vec3=[number,number,number];
type Quat=[number,number,number,number];

function normalized(value:string){return value.trim().toUpperCase();}
function anchorRank(anchor:AnchorDefinition){
  const status=anchor.status==='CONFIRMED'?0:anchor.status==='SUGGESTED'?1:2;
  const generated=anchor.autoGenerated?1:0;
  return status*10+generated;
}
function quatMultiply(a:Quat,b:Quat):Quat{
  const[ax,ay,az,aw]=a,[bx,by,bz,bw]=b;
  return[
    aw*bx+ax*bw+ay*bz-az*by,
    aw*by-ax*bz+ay*bw+az*bx,
    aw*bz+ax*by-ay*bx+az*bw,
    aw*bw-ax*bx-ay*by-az*bz,
  ];
}
function eulerQuaternion([x,y,z]:Vec3):Quat{
  const c1=Math.cos(x/2),c2=Math.cos(y/2),c3=Math.cos(z/2),s1=Math.sin(x/2),s2=Math.sin(y/2),s3=Math.sin(z/2);
  return[s1*c2*c3+c1*s2*s3,c1*s2*c3-s1*c2*s3,c1*c2*s3+s1*s2*c3,c1*c2*c3-s1*s2*s3];
}
function rotateVector([x,y,z]:Vec3,[qx,qy,qz,qw]:Quat):Vec3{
  const tx=2*(qy*z-qz*y),ty=2*(qz*x-qx*z),tz=2*(qx*y-qy*x);
  return[x+qw*tx+(qy*tz-qz*ty),y+qw*ty+(qz*tx-qx*tz),z+qw*tz+(qx*ty-qy*tx)];
}

export function findVariantPlacementAnchor(component:ComponentManifest,variant:ComponentVariant,anchors:AnchorDefinition[]=[]){
  const requested=normalized(variant.anchorType||'BOUNDS_CENTER');
  return anchors
    .filter(anchor=>anchor.componentId===component.id)
    .filter(anchor=>requested==='BOUNDS_CENTER'?anchor.kind==='BOUNDS_CENTER':normalized(anchor.connectionType||'GENERIC')===requested)
    .sort((a,b)=>anchorRank(a)-anchorRank(b)||b.confidence-a.confidence||a.id.localeCompare(b.id))[0];
}

/**
 * Places a variant whose authored origin is its mount point onto a target Manifest anchor.
 * Inputs/outputs are local to the target component parent, making the same rule usable by
 * Three.js preview and the GLB export worker without scene-graph parenting business state.
 */
export function resolveVariantAnchorTransform(input:{translation:Vec3;rotation:Quat;scale:Vec3;anchor?:AnchorDefinition}){
  if(!input.anchor)return{translation:[...input.translation] as Vec3,rotation:[...input.rotation] as Quat};
  const local:[number,number,number]=[
    input.anchor.positionMm[0]/1000*input.scale[0],
    input.anchor.positionMm[1]/1000*input.scale[1],
    input.anchor.positionMm[2]/1000*input.scale[2],
  ];
  const offset=rotateVector(local,input.rotation);
  return{
    translation:[input.translation[0]+offset[0],input.translation[1]+offset[1],input.translation[2]+offset[2]] as Vec3,
    rotation:quatMultiply(input.rotation,eulerQuaternion(input.anchor.rotation)),
  };
}

export function canApplyMaterial(component:ComponentManifest,material:MaterialPreset){
  const allowed=component.allowedMaterialCategories;
  return !allowed?.length || allowed.includes(material.category);
}

export function canApplyVariant(component:ComponentManifest,variant:ComponentVariant,modelTags:string[]=[],anchors:AnchorDefinition[]=[]){
  if(!component.variantGroupId || component.variantGroupId!==variant.groupId)return false;
  if(variant.compatibleComponentRoles.length&&!variant.compatibleComponentRoles.includes(component.role))return false;
  if(variant.compatibleModelTags.length){
    const available=new Set(modelTags.map(tag=>tag.trim().toLowerCase()).filter(Boolean));
    if(!variant.compatibleModelTags.some(tag=>available.has(tag.trim().toLowerCase())))return false;
  }
  const anchorType=normalized(variant.anchorType||'BOUNDS_CENTER');
  if(anchorType!=='BOUNDS_CENTER'&&!findVariantPlacementAnchor(component,variant,anchors))return false;
  return true;
}
