import type { AnchorDefinition,ComponentManifest,ComponentVariant,MaterialPreset } from '@product3d/model-schema';

function normalized(value:string){return value.trim().toUpperCase();}
function anchorRank(anchor:AnchorDefinition){
  const status=anchor.status==='CONFIRMED'?0:anchor.status==='SUGGESTED'?1:2;
  const generated=anchor.autoGenerated?1:0;
  return status*10+generated;
}

export function findVariantPlacementAnchor(component:ComponentManifest,variant:ComponentVariant,anchors:AnchorDefinition[]=[]){
  const requested=normalized(variant.anchorType||'BOUNDS_CENTER');
  return anchors
    .filter(anchor=>anchor.componentId===component.id)
    .filter(anchor=>requested==='BOUNDS_CENTER'?anchor.kind==='BOUNDS_CENTER':normalized(anchor.connectionType||'GENERIC')===requested)
    .sort((a,b)=>anchorRank(a)-anchorRank(b)||b.confidence-a.confidence||a.id.localeCompare(b.id))[0];
}

export function canApplyMaterial(component:ComponentManifest,material:MaterialPreset){
  const allowed=component.allowedMaterialCategories;
  return !allowed?.length || allowed.includes(material.category);
}

export function canApplyVariant(component:ComponentManifest,variant:ComponentVariant,modelTags:string[]=[],anchors:AnchorDefinition[]=[]){
  if(!component.variantGroupId || component.variantGroupId!==variant.groupId)return false;
  if(variant.compatibleComponentRoles.length&&!variant.compatibleComponentRoles.includes(component.role))return false;
  if(variant.compatibleModelTags.length){
    const available=new Set(modelTags.map(tag=>tag.trim().toLowerCase()).filter(Boolean));
    if(!variant.compatibleModelTags.some(tag=>available.has(tag.trim().toLowerCase())))return false;
  }
  const anchorType=normalized(variant.anchorType||'BOUNDS_CENTER');
  if(anchorType!=='BOUNDS_CENTER'&&!findVariantPlacementAnchor(component,variant,anchors))return false;
  return true;
}
