'use client';

import type {AnchorDefinition} from '@product3d/model-schema';
import {useEditorStore} from '../lib/store';
import {useSnapInteractionStore} from '../lib/snap-store';

const panelStyle={
  position:'fixed' as const,
  zIndex:40,
  width:310,
  maxWidth:'calc(100vw - 28px)',
  background:'rgba(10, 18, 28, 0.94)',
  border:'1px solid rgba(130, 157, 184, 0.3)',
  borderRadius:12,
  padding:12,
  color:'#eef5fb',
  fontSize:12,
  boxShadow:'0 12px 34px rgba(0,0,0,.28)',
  backdropFilter:'blur(12px)',
};

const controlStyle={
  width:'100%',
  boxSizing:'border-box' as const,
  background:'#0d1b29',
  border:'1px solid #30465a',
  borderRadius:6,
  color:'#eef5fb',
  padding:'5px 7px',
  fontSize:12,
};

function tupleValue(anchor:AnchorDefinition,key:'positionMm'|'rotation',index:number,value:number){
  const next=[...anchor[key]] as[number,number,number];next[index]=value;return next;
}

function AnchorEditor(){
  const store=useEditorStore();
  const definition=store.manifest?.components.find(item=>item.id===store.selected);
  if(!definition||!store.manifest)return null;
  const anchors=(store.manifest.anchors??[]).filter(anchor=>anchor.componentId===definition.id);
  const addManual=()=>{
    const id=`${definition.id}__manual_${Date.now().toString(36)}`;
    store.addAnchor({id,componentId:definition.id,name:'Manual anchor',kind:'POINT',positionMm:[0,0,0],rotation:[0,0,0],tags:['MANUAL'],connectionType:'CUSTOM',compatibleTypes:['CUSTOM'],autoGenerated:false,snapEnabled:true,alignRotation:false});
  };
  return <div style={{...panelStyle,top:126,right:356,maxHeight:'calc(100vh - 178px)',overflow:'auto'}} data-testid="anchor-editor-hud">
    <div style={{fontWeight:800,marginBottom:3}}>Anchor Setup · {definition.name}</div>
    <div style={{color:'#9db0c2',marginBottom:8}}>Auto draft có 7 anchor geometry. Đổi Connection type / Accepts để hệ thống biết part nào được phép gắn với nhau.</div>
    <div style={{display:'flex',gap:6,marginBottom:8,alignItems:'center'}}>
      <span style={{padding:'3px 6px',borderRadius:99,background:'#15324a'}}>{anchors.length} anchors</span>
      <button type="button" onClick={addManual} style={{...controlStyle,width:'auto',cursor:'pointer'}}>+ Manual anchor</button>
    </div>
    {anchors.map(anchor=><details key={anchor.id} style={{borderTop:'1px solid rgba(130,157,184,.2)',padding:'7px 0'}}>
      <summary style={{cursor:'pointer',fontWeight:700}}>{anchor.name??anchor.id} · {anchor.connectionType}</summary>
      <div style={{display:'grid',gap:6,marginTop:7}}>
        <label>Name<input style={controlStyle} value={anchor.name??''} onChange={event=>store.patchAnchor(anchor.id,{name:event.target.value})}/></label>
        <label>Kind<select style={controlStyle} value={anchor.kind} onChange={event=>store.patchAnchor(anchor.id,{kind:event.target.value as AnchorDefinition['kind']})}><option>POINT</option><option>PLANE</option><option>AXIS</option><option>BOUNDS_CENTER</option></select></label>
        <label>Connection type<input style={controlStyle} value={anchor.connectionType} onChange={event=>store.patchAnchor(anchor.id,{connectionType:event.target.value.trim().toUpperCase()||'GENERIC'})}/></label>
        <label>Accepts types<input style={controlStyle} value={anchor.compatibleTypes.join(', ')} onChange={event=>store.patchAnchor(anchor.id,{compatibleTypes:event.target.value.split(',').map(item=>item.trim().toUpperCase()).filter(Boolean)})}/></label>
        <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:4}}>
          {(['X','Y','Z'] as const).map((axis,index)=><label key={axis}>Pos {axis} mm<input type="number" style={controlStyle} value={Math.round(anchor.positionMm[index]*1000)/1000} onChange={event=>store.patchAnchor(anchor.id,{positionMm:tupleValue(anchor,'positionMm',index,Number(event.target.value))})}/></label>)}
        </div>
        <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:4}}>
          {(['X','Y','Z'] as const).map((axis,index)=><label key={axis}>Rot {axis}°<input type="number" style={controlStyle} value={Math.round(anchor.rotation[index]*18000/Math.PI)/100} onChange={event=>store.patchAnchor(anchor.id,{rotation:tupleValue(anchor,'rotation',index,Number(event.target.value)*Math.PI/180)})}/></label>)}
        </div>
        <label style={{display:'flex',gap:6,alignItems:'center'}}><input type="checkbox" checked={anchor.snapEnabled} onChange={event=>store.patchAnchor(anchor.id,{snapEnabled:event.target.checked})}/>Snap enabled</label>
        <label style={{display:'flex',gap:6,alignItems:'center'}}><input type="checkbox" checked={anchor.alignRotation} onChange={event=>store.patchAnchor(anchor.id,{alignRotation:event.target.checked})}/>Align rotation when snapping</label>
        <label>Tags<input style={controlStyle} value={anchor.tags.join(', ')} onChange={event=>store.patchAnchor(anchor.id,{tags:event.target.value.split(',').map(item=>item.trim()).filter(Boolean)})}/></label>
        {!anchor.autoGenerated&&<button type="button" style={{...controlStyle,cursor:'pointer'}} onClick={()=>store.removeAnchor(anchor.id)}>Remove anchor</button>}
      </div>
    </details>)}
    <div style={{marginTop:7,color:'#9db0c2'}}>Ví dụ: WING_ROOT accepts WING_MOUNT. GENERIC ↔ GENERIC vẫn snap được nhưng chỉ dựa vào geometry.</div>
  </div>;
}

function SnapStatus(){
  const store=useEditorStore();
  const snap=useSnapInteractionStore();
  const definition=store.manifest?.components.find(item=>item.id===store.selected);
  const attachment=store.selected?(store.configuration?.attachments??[]).find(item=>item.sourceComponentId===store.selected):undefined;
  const target=attachment?store.manifest?.components.find(item=>item.id===attachment.targetComponentId):undefined;
  const sourceAnchor=attachment?(store.manifest?.anchors??[]).find(item=>item.id===attachment.sourceAnchorId):undefined;
  const targetAnchor=attachment?(store.manifest?.anchors??[]).find(item=>item.id===attachment.targetAnchorId):undefined;
  if(!snap.candidate&&!attachment)return null;
  return <div className="snap-status-card" data-testid="snap-status-hud">
    {snap.candidate&&<div className={snap.candidate.ready?'snap-ready':'snap-nearest'}>
      <div className="snap-status-title">{snap.candidate.ready?'Ready to snap':'Nearest part'} · {snap.candidate.targetComponentName}</div>
      <div>{snap.candidate.sourceAnchorName} → {snap.candidate.targetAnchorName} · <b>{Math.round(snap.candidate.gapMm)} mm</b></div>
      {!snap.candidate.compatible&&<span>Anchor types incompatible — indicator only, no magnetic snap.</span>}
    </div>}
    {attachment&&<div className="attachment-status">
      <div className="snap-status-title">Attached · {definition?.name} → {target?.name??attachment.targetComponentId}</div>
      <div>{sourceAnchor?.name??attachment.sourceAnchorId} → {targetAnchor?.name??attachment.targetAnchorId}</div>
      <button type="button" onClick={()=>store.dispatch({type:'DETACH_COMPONENT',componentId:attachment.sourceComponentId,source:'MANUAL'},'Detach component')}>Detach</button>
    </div>}
  </div>;
}

export default function SnapViewportHud(){
  const phase=useEditorStore(state=>state.phase);
  return phase==='PREPARE'?<AnchorEditor/>:phase==='EDITOR'?<SnapStatus/>:null;
}
