'use client';

import type { AnchorDefinition } from '@product3d/model-schema';
import { useEditorStore } from '../lib/store';
import { useSnapInteractionStore } from '../lib/snap-store';

const panelStyle = {
  position: 'fixed' as const,
  zIndex: 50,
  width: 310,
  maxWidth: 'calc(100vw - 28px)',
  background: 'rgba(8, 17, 28, 0.96)',
  border: '1px solid rgba(130, 157, 184, 0.35)',
  borderRadius: 10,
  padding: 10,
  color: '#eef5fb',
  fontSize: 12,
  boxShadow: '0 8px 24px rgba(0,0,0,.28)',
};

const controlStyle = {
  width: '100%',
  boxSizing: 'border-box' as const,
  background: '#0d1b29',
  border: '1px solid #30465a',
  borderRadius: 6,
  color: '#eef5fb',
  padding: '5px 7px',
  fontSize: 12,
};

function tupleValue(anchor:AnchorDefinition,key:'positionMm'|'rotation',index:number,value:number){
  const next=[...anchor[key]] as [number,number,number];next[index]=value;return next;
}

function AnchorEditor(){
  const store=useEditorStore();
  const definition=store.manifest?.components.find(item=>item.id===store.selected);
  if(!definition||!store.manifest)return null;
  const anchors=(store.manifest.anchors??[]).filter(anchor=>anchor.componentId===definition.id);
  const addManual=()=>{
    const id=`${definition.id}__manual_${Date.now().toString(36)}`;
    store.addAnchor({id,componentId:definition.id,name:'Manual anchor',kind:'POINT',positionMm:[0,0,0],rotation:[0,0,0],tags:['MANUAL'],connectionType:'CUSTOM',compatibleTypes:['CUSTOM'],autoGenerated:false,snapEnabled:true,alignRotation:false});
  };
  return <div style={{...panelStyle,top:138,right:14,maxHeight:'calc(100vh - 180px)',overflow:'auto'}} data-testid="anchor-editor-hud">
    <div style={{fontWeight:800,marginBottom:3}}>Anchor Setup · {definition.name}</div>
    <div style={{color:'#9db0c2',marginBottom:8}}>Auto draft có 7 anchor geometry. Đổi Connection type / Accepts để hệ thống biết part nào được phép gắn với nhau.</div>
    <div style={{display:'flex',gap:6,marginBottom:8,alignItems:'center'}}>
      <span style={{padding:'3px 6px',borderRadius:99,background:'#15324a'}}>{anchors.length} anchors</span>
      <button type="button" onClick={addManual} style={{...controlStyle,width:'auto',cursor:'pointer'}}>+ Manual anchor</button>
    </div>
    {anchors.map(anchor=><details key={anchor.id} style={{borderTop:'1px solid rgba(130,157,184,.2)',padding:'7px 0'}}>
      <summary style={{cursor:'pointer',fontWeight:700}}>{anchor.name??anchor.id} · {anchor.connectionType}</summary>
      <div style={{display:'grid',gap:6,marginTop:7}}>
        <label>Name<input style={controlStyle} value={anchor.name??''} onChange={event=>store.patchAnchor(anchor.id,{name:event.target.value})}/></label>
        <label>Kind<select style={controlStyle} value={anchor.kind} onChange={event=>store.patchAnchor(anchor.id,{kind:event.target.value as AnchorDefinition['kind']})}><option>POINT</option><option>PLANE</option><option>AXIS</option><option>BOUNDS_CENTER</option></select></label>
        <label>Connection type<input style={controlStyle} value={anchor.connectionType} onChange={event=>store.patchAnchor(anchor.id,{connectionType:event.target.value.trim().toUpperCase()||'GENERIC'})}/></label>
        <label>Accepts types<input style={controlStyle} value={anchor.compatibleTypes.join(', ')} onChange={event=>store.patchAnchor(anchor.id,{compatibleTypes:event.target.value.split(',').map(item=>item.trim().toUpperCase()).filter(Boolean)})}/></label>
        <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:4}}>
          {(['X','Y','Z'] as const).map((axis,index)=><label key={axis}>Pos {axis} mm<input type="number" style={controlStyle} value={Math.round(anchor.positionMm[index]*1000)/1000} onChange={event=>store.patchAnchor(anchor.id,{positionMm:tupleValue(anchor,'positionMm',index,Number(event.target.value))})}/></label>)}
        </div>
        <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:4}}>
          {(['X','Y','Z'] as const).map((axis,index)=><label key={axis}>Rot {axis}°<input type="number" style={controlStyle} value={Math.round(anchor.rotation[index]*18000/Math.PI)/100} onChange={event=>store.patchAnchor(anchor.id,{rotation:tupleValue(anchor,'rotation',index,Number(event.target.value)*Math.PI/180)})}/></label>)}
        </div>
        <label style={{display:'flex',gap:6,alignItems:'center'}}><input type="checkbox" checked={anchor.snapEnabled} onChange={event=>store.patchAnchor(anchor.id,{snapEnabled:event.target.checked})}/>Snap enabled</label>
        <label style={{display:'flex',gap:6,alignItems:'center'}}><input type="checkbox" checked={anchor.alignRotation} onChange={event=>store.patchAnchor(anchor.id,{alignRotation:event.target.checked})}/>Align rotation when snapping</label>
        <label>Tags<input style={controlStyle} value={anchor.tags.join(', ')} onChange={event=>store.patchAnchor(anchor.id,{tags:event.target.value.split(',').map(item=>item.trim()).filter(Boolean)})}/></label>
        {!anchor.autoGenerated&&<button type="button" style={{...controlStyle,cursor:'pointer'}} onClick={()=>store.removeAnchor(anchor.id)}>Remove anchor</button>}
      </div>
    </details>)}
    <div style={{marginTop:7,color:'#9db0c2'}}>Ví dụ: WING_ROOT accepts WING_MOUNT. GENERIC ↔ GENERIC vẫn snap được nhưng chỉ dựa vào geometry.</div>
  </div>;
}

function SnapStatus(){
  const store=useEditorStore();
  const snap=useSnapInteractionStore();
  const definition=store.manifest?.components.find(item=>item.id===store.selected);
  const attachment=store.selected?(store.configuration?.attachments??[]).find(item=>item.sourceComponentId===store.selected):undefined;
  const target=attachment?store.manifest?.components.find(item=>item.id===attachment.targetComponentId):undefined;
  const sourceAnchor=attachment?(store.manifest?.anchors??[]).find(item=>item.id===attachment.sourceAnchorId):undefined;
  const targetAnchor=attachment?(store.manifest?.anchors??[]).find(item=>item.id===attachment.targetAnchorId):undefined;
  return <div style={{...panelStyle,left:270,top:138,width:285}} data-testid="snap-status-hud">
    <div style={{display:'flex',gap:6,alignItems:'center',flexWrap:'wrap'}}>
      <button type="button" onClick={snap.toggleSnap} style={{...controlStyle,width:'auto',cursor:'pointer'}}><b>S</b> · Snap {snap.snapEnabled?'ON':'OFF'}</button>
      <button type="button" onClick={snap.toggleLabels} style={{...controlStyle,width:'auto',cursor:'pointer'}}><b>L</b> · Labels {snap.labelsVisible?'ON':'OFF'}</button>
    </div>
    {snap.candidate&&<div style={{marginTop:8,padding:7,borderRadius:7,background:snap.candidate.ready?'rgba(43,117,70,.35)':'rgba(135,99,33,.28)'}}>
      <b>{snap.candidate.ready?'Ready to snap':'Nearest part'}:</b> {snap.candidate.targetComponentName}<br/>
      {snap.candidate.sourceAnchorName} → {snap.candidate.targetAnchorName} · {Math.round(snap.candidate.gapMm)} mm<br/>
      {!snap.candidate.compatible&&<span style={{color:'#ffd28a'}}>Anchor types incompatible — indicator only, no magnetic snap.</span>}
    </div>}
    {attachment&&<div style={{marginTop:8,padding:7,borderRadius:7,background:'rgba(36,87,121,.35)'}}>
      <b>Attached:</b> {definition?.name} → {target?.name??attachment.targetComponentId}<br/>
      {sourceAnchor?.name??attachment.sourceAnchorId} → {targetAnchor?.name??attachment.targetAnchorId}
      <button type="button" style={{...controlStyle,marginTop:6,cursor:'pointer'}} onClick={()=>store.dispatch({type:'DETACH_COMPONENT',componentId:attachment.sourceComponentId,source:'MANUAL'},'Detach component')}>Detach</button>
    </div>}
    {!snap.candidate&&!attachment&&<div style={{marginTop:7,color:'#9db0c2'}}>Move một part lại gần part khác để hiện nearest indicator + gap mm. Thả khi READY TO SNAP để gắn.</div>}
  </div>;
}

export default function SnapViewportHud(){
  const phase=useEditorStore(state=>state.phase);
  return phase==='PREPARE'?<AnchorEditor/>:phase==='EDITOR'?<SnapStatus/>:null;
}
