'use client';

import type {AnchorDefinition,AnchorStatus} from '@product3d/model-schema';
import {useEditorStore} from '../lib/store';
import {useSnapInteractionStore} from '../lib/snap-store';

const panelStyle={
  position:'fixed' as const,
  zIndex:40,
  width:310,
  maxWidth:'calc(100vw - 28px)',
  background:'rgba(10, 18, 28, 0.94)',
  border:'1px solid rgba(130, 157, 184, 0.3)',
  borderRadius:12,
  padding:12,
  color:'#eef5fb',
  fontSize:12,
  boxShadow:'0 12px 34px rgba(0,0,0,.28)',
  backdropFilter:'blur(12px)',
};

const controlStyle={
  width:'100%',
  boxSizing:'border-box' as const,
  background:'#0d1b29',
  border:'1px solid #30465a',
  borderRadius:6,
  color:'#eef5fb',
  padding:'5px 7px',
  fontSize:12,
};

const allAxes={x:true,y:true,z:true};
function list(value:string){return value.split(',').map(item=>item.trim()).filter(Boolean);}
function tupleValue(anchor:AnchorDefinition,key:'positionMm'|'rotation',index:number,value:number){
  const next=[...anchor[key]] as[number,number,number];next[index]=value;return next;
}

function AnchorEditor(){
  const store=useEditorStore();
  const definition=store.manifest?.components.find(item=>item.id===store.selected);
  if(!definition||!store.manifest)return null;
  const anchors=(store.manifest.anchors??[]).filter(anchor=>anchor.componentId===definition.id);
  const positionAxes=definition.positionEditableAxes??allAxes;
  const rotationAxes=definition.rotationEditableAxes??allAxes;
  const setTransformAxis=(kind:'position'|'rotation',axis:'x'|'y'|'z',checked:boolean)=>{
    if(kind==='position')store.patchComponentDefinition(definition.id,{positionEditableAxes:{...positionAxes,[axis]:checked}});
    else store.patchComponentDefinition(definition.id,{rotationEditableAxes:{...rotationAxes,[axis]:checked}});
  };
  const setModelTags=(value:string)=>useEditorStore.setState(state=>state.manifest?{manifest:{...state.manifest,modelTags:list(value)}}:{});
  const addManual=()=>{
    const id=`${definition.id}__manual_${Date.now().toString(36)}`;
    store.addAnchor({id,componentId:definition.id,name:'Manual anchor',kind:'POINT',positionMm:[0,0,0],rotation:[0,0,0],tags:['MANUAL'],connectionType:'CUSTOM',compatibleTypes:['CUSTOM'],autoGenerated:false,status:'CONFIRMED',confidence:1,snapEnabled:true,alignRotation:false});
  };
  return <div style={{...panelStyle,top:126,right:356,maxHeight:'calc(100vh - 178px)',overflow:'auto'}} data-testid="anchor-editor-hud">
    <div style={{fontWeight:800,marginBottom:3}}>Component Setup · {definition.name}</div>
    <div style={{color:'#9db0c2',marginBottom:8}}>Transform permission, style metadata và semantic anchor đều thuộc Manifest. Model tags được dùng cho variant compatibility; component style tags được dùng cho style/catalog matching.</div>

    <div style={{borderTop:'1px solid rgba(130,157,184,.2)',borderBottom:'1px solid rgba(130,157,184,.2)',padding:'8px 0',marginBottom:8}} data-testid="manifest-style-metadata">
      <div style={{fontWeight:800,marginBottom:5}}>Style & compatibility metadata</div>
      <label>Model tags<input style={controlStyle} value={(store.manifest.modelTags??[]).join(', ')} placeholder="aircraft, premium, outdoor" onChange={event=>setModelTags(event.target.value)}/></label>
      <label>Component style tags<input style={controlStyle} value={(definition.styleTags??[]).join(', ')} placeholder="modern, minimal, structural" onChange={event=>store.patchComponentDefinition(definition.id,{styleTags:list(event.target.value)})}/></label>
    </div>

    <div style={{borderTop:'1px solid rgba(130,157,184,.2)',borderBottom:'1px solid rgba(130,157,184,.2)',padding:'8px 0',marginBottom:8}} data-testid="transform-permission-editor">
      <div style={{fontWeight:800,marginBottom:5}}>Transform permissions</div>
      <div style={{color:'#9db0c2',marginBottom:6}}>Move/Rotate có permission riêng với Resize. Tắt trục ở đây sẽ khóa cả gizmo lẫn numeric Channel Box.</div>
      {(['position','rotation'] as const).map(kind=>{
        const axes=kind==='position'?positionAxes:rotationAxes;
        return <div key={kind} style={{display:'grid',gridTemplateColumns:'78px repeat(3,1fr)',gap:5,alignItems:'center',marginBottom:5}}>
          <strong>{kind==='position'?'Move':'Rotate'}</strong>
          {(['x','y','z'] as const).map(axis=><label key={axis} style={{display:'flex',gap:4,alignItems:'center'}}><input type="checkbox" disabled={!definition.editable} checked={axes[axis]} onChange={event=>setTransformAxis(kind,axis,event.target.checked)}/>{axis.toUpperCase()}</label>)}
        </div>;
      })}
      <div style={{display:'flex',gap:6,marginTop:6}}>
        <button type="button" style={{...controlStyle,width:'auto',cursor:'pointer'}} disabled={!definition.editable} onClick={()=>store.patchComponentDefinition(definition.id,{positionEditableAxes:{...allAxes},rotationEditableAxes:{...allAxes}})}>Allow all</button>
        <button type="button" style={{...controlStyle,width:'auto',cursor:'pointer'}} disabled={!definition.editable} onClick={()=>store.patchComponentDefinition(definition.id,{positionEditableAxes:{x:false,y:false,z:false},rotationEditableAxes:{x:false,y:false,z:false}})}>Lock transform</button>
      </div>
    </div>

    <div style={{fontWeight:800,marginBottom:3}}>Anchor Setup</div>
    <div style={{color:'#9db0c2',marginBottom:8}}>Auto anchors chỉ là geometry draft. Review semantic type và chuyển anchor quan trọng sang CONFIRMED trước khi dùng cho assembly hoặc semantic variant placement.</div>
    <div style={{display:'flex',gap:6,marginBottom:8,alignItems:'center'}}>
      <span style={{padding:'3px 6px',borderRadius:99,background:'#15324a'}}>{anchors.length} anchors</span>
      <span style={{padding:'3px 6px',borderRadius:99,background:'#15324a'}}>{anchors.filter(item=>item.status==='CONFIRMED').length} confirmed</span>
      <button type="button" onClick={addManual} style={{...controlStyle,width:'auto',cursor:'pointer'}}>+ Manual anchor</button>
    </div>
    {anchors.map(anchor=><details key={anchor.id} style={{borderTop:'1px solid rgba(130,157,184,.2)',padding:'7px 0'}}>
      <summary style={{cursor:'pointer',fontWeight:700}}>{anchor.name??anchor.id} · {anchor.connectionType} · {anchor.status}</summary>
      <div style={{display:'grid',gap:6,marginTop:7}}>
        <label>Name<input style={controlStyle} value={anchor.name??''} onChange={event=>store.patchAnchor(anchor.id,{name:event.target.value})}/></label>
        <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6}}>
          <label>Status<select style={controlStyle} value={anchor.status} onChange={event=>store.patchAnchor(anchor.id,{status:event.target.value as AnchorStatus})}><option>AUTO</option><option>SUGGESTED</option><option>CONFIRMED</option></select></label>
          <label>Confidence<input type="number" min="0" max="1" step="0.05" style={controlStyle} value={anchor.confidence} onChange={event=>store.patchAnchor(anchor.id,{confidence:Math.max(0,Math.min(1,Number(event.target.value)))})}/></label>
        </div>
        <label>Kind<select style={controlStyle} value={anchor.kind} onChange={event=>store.patchAnchor(anchor.id,{kind:event.target.value as AnchorDefinition['kind']})}><option>POINT</option><option>PLANE</option><option>AXIS</option><option>BOUNDS_CENTER</option></select></label>
        <label>Connection type<input style={controlStyle} value={anchor.connectionType} onChange={event=>store.patchAnchor(anchor.id,{connectionType:event.target.value.trim().toUpperCase()||'GENERIC'})}/></label>
        <label>Accepts types<input style={controlStyle} value={anchor.compatibleTypes.join(', ')} onChange={event=>store.patchAnchor(anchor.id,{compatibleTypes:list(event.target.value).map(item=>item.toUpperCase())})}/></label>
        <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:4}}>
          {(['X','Y','Z'] as const).map((axis,index)=><label key={axis}>Pos {axis} mm<input type="number" style={controlStyle} value={Math.round(anchor.positionMm[index]*1000)/1000} onChange={event=>store.patchAnchor(anchor.id,{positionMm:tupleValue(anchor,'positionMm',index,Number(event.target.value))})}/></label>)}
        </div>
        <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:4}}>
          {(['X','Y','Z'] as const).map((axis,index)=><label key={axis}>Rot {axis}°<input type="number" style={controlStyle} value={Math.round(anchor.rotation[index]*18000/Math.PI)/100} onChange={event=>store.patchAnchor(anchor.id,{rotation:tupleValue(anchor,'rotation',index,Number(event.target.value)*Math.PI/180)})}/></label>)}
        </div>
        <label style={{display:'flex',gap:6,alignItems:'center'}}><input type="checkbox" checked={anchor.snapEnabled} onChange={event=>store.patchAnchor(anchor.id,{snapEnabled:event.target.checked})}/>Snap enabled</label>
        <label style={{display:'flex',gap:6,alignItems:'center'}}><input type="checkbox" checked={anchor.alignRotation} onChange={event=>store.patchAnchor(anchor.id,{alignRotation:event.target.checked})}/>Align rotation when snapping</label>
        <label>Tags<input style={controlStyle} value={anchor.tags.join(', ')} onChange={event=>store.patchAnchor(anchor.id,{tags:list(event.target.value)})}/></label>
        {!anchor.autoGenerated&&<button type="button" style={{...controlStyle,cursor:'pointer'}} onClick={()=>store.removeAnchor(anchor.id)}>Remove anchor</button>}
      </div>
    </details>)}
    <div style={{marginTop:7,color:'#9db0c2'}}>Variant có anchorType semantic sẽ chỉ replace khi component có anchor tương ứng. Variant GLB được author với origin tại mount point; viewer và export cùng map origin đó vào Manifest anchor.</div>
  </div>;
}

function SnapStatus(){
  const store=useEditorStore();
  const snap=useSnapInteractionStore();
  const definition=store.manifest?.components.find(item=>item.id===store.selected);
  const attachment=store.selected?(store.configuration?.attachments??[]).find(item=>item.sourceComponentId===store.selected):undefined;
  const target=attachment?store.manifest?.components.find(item=>item.id===attachment.targetComponentId):undefined;
  const sourceAnchor=attachment?(store.manifest?.anchors??[]).find(item=>item.id===attachment.sourceAnchorId):undefined;
  const targetAnchor=attachment?(store.manifest?.anchors??[]).find(item=>item.id===attachment.targetAnchorId):undefined;
  if(!snap.candidate&&!attachment&&!snap.groundBarrier&&!snap.attachMode)return null;
  const readyTitle=snap.attachMode?'Ready to attach':'Snap preview';
  return <div className="snap-status-card" data-testid="snap-status-hud">
    {snap.attachMode&&!snap.candidate&&<div className="snap-nearest" data-testid="attach-mode-armed">
      <div className="snap-status-title">Attach mode armed</div>
      <div>Move {definition?.name??'the selected part'} gần một compatible anchor. Thả chuột khi preview chuyển sang Ready to attach.</div>
      <span>Esc để hủy Attach mode. Sau khi attach thành công mode sẽ tự tắt.</span>
    </div>}
    {snap.groundBarrier&&<div className={`ground-barrier-status ${snap.groundBarrier.phase}`} data-testid="ground-barrier-status">
      <div className="snap-status-title">{snap.groundBarrier.phase==='resisting'?'Ground barrier · Y = 0':'Ground barrier released'}</div>
      {snap.groundBarrier.phase==='resisting'
        ?<><div>{snap.groundBarrier.componentName} đang chạm mặt lưới. Tiếp tục kéo xuống để cố ý xuyên qua.</div><div className="ground-barrier-meter"><span style={{width:`${Math.round(snap.groundBarrier.progress*100)}%`}}/></div><small>{Math.round(snap.groundBarrier.penetrationMm)} / {Math.round(snap.groundBarrier.thresholdMm)} mm lực kéo xuyên</small></>
        :<div>{snap.groundBarrier.componentName} đã vượt ngưỡng — cho phép đi xuống dưới mặt lưới.</div>}
    </div>}
    {snap.candidate&&<div className={snap.candidate.ready?'snap-ready':'snap-nearest'}>
      <div className="snap-status-title">{snap.candidate.ready?readyTitle:'Candidate'} · {snap.candidate.targetComponentName}</div>
      <div>{snap.candidate.sourceAnchorName} → {snap.candidate.targetAnchorName} · <b>{Math.round(snap.candidate.gapMm)} mm</b></div>
      {!snap.candidate.compatible&&<span>Anchor types incompatible — indicator only, không snap.</span>}
      {snap.candidate.compatible&&snap.candidate.ready&&<span>{snap.attachMode?'Release → snap vị trí + tạo attachment.':'Release → chỉ snap vị trí. Không tạo relationship.'}</span>}
      {snap.temporarySnapActive&&!snap.attachMode&&<span>Temporary Ctrl Snap đang active.</span>}
    </div>}
    {attachment&&<div className="attachment-status">
      <div className="snap-status-title">Attached · {definition?.name} → {target?.name??attachment.targetComponentId}</div>
      <div>{sourceAnchor?.name??attachment.sourceAnchorId} → {targetAnchor?.name??attachment.targetAnchorId}</div>
      <span>Move/Rotate source part sẽ phá alignment và engine hiện detach relationship khi transform commit. Dùng Detach trước để thể hiện intent rõ ràng.</span>
      <button type="button" onClick={()=>store.dispatch({type:'DETACH_COMPONENT',componentId:attachment.sourceComponentId,source:'MANUAL'},'Detach component')}>Detach</button>
    </div>}
  </div>;
}

export default function SnapViewportHud(){
  const phase=useEditorStore(state=>state.phase);
  return phase==='PREPARE'?<AnchorEditor/>:phase==='EDITOR'?<SnapStatus/>:null;
}
