import {BadRequestException,Body,Controller,Get,NotFoundException,Param,Post,Put,Query,Req,UseGuards} from '@nestjs/common';
import {ModelManifestSchema} from '@product3d/model-schema';
import {randomUUID} from 'node:crypto';import {z} from 'zod';
import {AuthRequest,requireAuthUser,SupabaseAuthGuard} from '../auth/auth.service';import {PrismaService} from '../prisma/prisma.service';import {AssetQueueService} from '../queue/asset-queue.service';import {StorageService} from '../storage/storage.service';
const MAX_ASSET_BYTES=Number(process.env.MAX_ASSET_BYTES??250*1024*1024);const ImportAssetSchema=z.object({name:z.string().trim().min(1).max(120).optional(),originalFilename:z.string().trim().min(1).max(255),contentType:z.string().trim().min(1).max(120).default('model/gltf-binary'),sizeBytes:z.number().int().positive().max(MAX_ASSET_BYTES).optional()});function safeFilename(filename:string){return filename.replace(/[^a-zA-Z0-9._-]+/g,'_').replace(/^\.+/,'').slice(0,180)||'model.glb'}
@Controller('assets') @UseGuards(SupabaseAuthGuard)
export class AssetController{
 constructor(private readonly db:PrismaService,private readonly storage:StorageService,private readonly assetQueue:AssetQueueService){}
 private async owned(id:string,userId:string){const asset=await this.db.modelAsset.findFirst({where:{id,ownerId:userId}});if(!asset)throw new NotFoundException('Asset not found.');return asset;}
 @Get() list(@Req()r:AuthRequest){const user=requireAuthUser(r);return this.db.modelAsset.findMany({where:{ownerId:user.id},orderBy:{updatedAt:'desc'},select:{id:true,name:true,originalFilename:true,status:true,sizeBytes:true,thumbnailUrl:true,createdAt:true,updatedAt:true,_count:{select:{manifests:true,projects:true}}}})}
 @Post('import') async importAsset(@Req()request:AuthRequest,@Body()body:unknown){const user=requireAuthUser(request),parsed=ImportAssetSchema.safeParse(body);if(!parsed.success)throw new BadRequestException(parsed.error.flatten());const input=parsed.data;if(!input.originalFilename.toLowerCase().endsWith('.glb'))throw new BadRequestException('Phase 1 production upload accepts .glb only.');const id=randomUUID(),sourceObjectKey=`assets/${user.id}/${id}/source/${safeFilename(input.originalFilename)}`;const asset=await this.db.modelAsset.create({data:{id,ownerId:user.id,name:input.name??input.originalFilename.replace(/\.glb$/i,''),originalFilename:input.originalFilename,contentType:input.contentType,sizeBytes:input.sizeBytes,sourceObjectKey,sourceUrl:this.storage.objectUri(sourceObjectKey),status:'AWAITING_UPLOAD'}});return{asset,upload:await this.storage.createUploadGrant(sourceObjectKey)};}
 @Get(':id') get(@Req()r:AuthRequest,@Param('id')id:string){return this.owned(id,requireAuthUser(r).id)}
 private async enqueueAnalysis(id:string,userId:string){const asset=await this.owned(id,userId);if(!asset.sourceObjectKey)throw new BadRequestException('Asset has no source object key.');try{await this.storage.assertObjectExists(asset.sourceObjectKey)}catch{throw new BadRequestException('Uploaded GLB was not found in Supabase Storage.');}const databaseJob=await this.db.job.create({data:{type:'ASSET_ANALYZE_NORMALIZE',status:'QUEUED',modelAssetId:id,payload:{assetId:id,sourceObjectKey:asset.sourceObjectKey,originalFilename:asset.originalFilename}}});try{const queued=await this.assetQueue.enqueue({assetId:id,databaseJobId:databaseJob.id,sourceObjectKey:asset.sourceObjectKey,originalFilename:asset.originalFilename});await this.db.$transaction([this.db.job.update({where:{id:databaseJob.id},data:{bullmqJobId:String(queued.id)}}),this.db.modelAsset.update({where:{id},data:{status:'QUEUED'}})]);return{jobId:databaseJob.id,status:'QUEUED'}}catch(error){await this.db.job.update({where:{id:databaseJob.id},data:{status:'FAILED',failureReason:error instanceof Error?error.message:String(error)}});throw error}}
 @Post(':id/analyze') analyze(@Req()r:AuthRequest,@Param('id')id:string){return this.enqueueAnalysis(id,requireAuthUser(r).id)}
 @Post(':id/normalize') normalize(@Req()r:AuthRequest,@Param('id')id:string){return this.enqueueAnalysis(id,requireAuthUser(r).id)}
 @Get(':id/analysis') async analysis(@Req()r:AuthRequest,@Param('id')id:string){const asset=await this.owned(id,requireAuthUser(r).id);if(!asset.analysisJson)throw new NotFoundException('Asset analysis is not available yet.');return asset.analysisJson}
 @Get(':id/download') async download(@Req()r:AuthRequest,@Param('id')id:string,@Query('kind')kind='normalized'){const asset=await this.owned(id,requireAuthUser(r).id),objectKey=kind==='source'?asset.sourceObjectKey:asset.normalizedObjectKey;if(!objectKey)throw new NotFoundException(`${kind} asset is not available.`);return{url:await this.storage.createDownloadUrl(objectKey),expiresInSeconds:900}}
 @Get(':id/manifest') async getManifest(@Req()r:AuthRequest,@Param('id')id:string){await this.owned(id,requireAuthUser(r).id);return this.db.modelManifest.findFirst({where:{modelAssetId:id},orderBy:{version:'desc'}})}
 @Put(':id/manifest') async saveManifest(@Req()r:AuthRequest,@Param('id')id:string,@Body()body:{manifestJson:unknown}){await this.owned(id,requireAuthUser(r).id);const parsed=ModelManifestSchema.safeParse(body.manifestJson);if(!parsed.success)throw new BadRequestException(parsed.error.flatten());const latest=await this.db.modelManifest.findFirst({where:{modelAssetId:id},orderBy:{version:'desc'}});return this.db.modelManifest.create({data:{modelAssetId:id,version:(latest?.version??0)+1,manifestJson:parsed.data}})}
}