ALTER TABLE "ComponentVariant" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true;
CREATE TABLE "StylePreset"("id" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"styleTags" TEXT[],"rulesJson" JSONB NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,CONSTRAINT "StylePreset_pkey" PRIMARY KEY("id"));
CREATE TABLE "UserPreset"("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"name" TEXT NOT NULL,"rulesJson" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "UserPreset_pkey" PRIMARY KEY("id"));
ALTER TABLE "UserPreset" ADD CONSTRAINT "UserPreset_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
